-- generated by scripts/missions-json-to-sql.mjs from data/global_mission.json
-- valid_from = day 12:00 UTC, valid_to = 다음날 12:00 UTC
-- 이미 같은 mission_date에 published 가 있으면 유니크 충돌 → 해당 날짜 정리 후 실행

begin;

insert into public.missions (
  mission_date,
  category_key,
  title,
  short_description,
  notice_text,
  is_time_sensitive,
  status,
  valid_from,
  valid_to
) values (
  '2026-05-01'::date,
  'food',
  '우리 동네 한 끼 소개',
  '현지에서 사람들이 가장 자주 먹는 한 끼 식사를 사진으로 보여주세요. 음식 자체가 잘 보이게 찍어주면 좋아요.',
  ''::text,
  false,
  'published',
  '2026-05-01 12:00:00+00'::timestamptz,
  '2026-05-02 12:00:00+00'::timestamptz
);

insert into public.missions (
  mission_date,
  category_key,
  title,
  short_description,
  notice_text,
  is_time_sensitive,
  status,
  valid_from,
  valid_to
) values (
  '2026-05-02'::date,
  'food',
  '길거리 음식 1개 추천',
  '관광객보다 현지인이 더 자주 사 먹는 길거리 음식을 사진으로 보여주세요. 음식 자체가 잘 보이게 찍어주면 좋아요.',
  ''::text,
  false,
  'published',
  '2026-05-02 12:00:00+00'::timestamptz,
  '2026-05-03 12:00:00+00'::timestamptz
);

insert into public.missions (
  mission_date,
  category_key,
  title,
  short_description,
  notice_text,
  is_time_sensitive,
  status,
  valid_from,
  valid_to
) values (
  '2026-05-03'::date,
  'food',
  '아침 식사 문화 보여주기',
  '당신의 나라에서 흔한 아침 메뉴를 사진으로 보여주고 왜 그렇게 먹는지 짧게 설명해주세요. 음식 자체가 잘 보이게 찍어주면 좋아요.',
  ''::text,
  false,
  'published',
  '2026-05-03 12:00:00+00'::timestamptz,
  '2026-05-04 12:00:00+00'::timestamptz
);

insert into public.missions (
  mission_date,
  category_key,
  title,
  short_description,
  notice_text,
  is_time_sensitive,
  status,
  valid_from,
  valid_to
) values (
  '2026-05-04'::date,
  'food',
  '집밥의 기본 반찬/사이드',
  '가정식에서 자주 함께 나오는 반찬이나 사이드를 사진으로 보여주세요. 음식 자체가 잘 보이게 찍어주면 좋아요.',
  ''::text,
  false,
  'published',
  '2026-05-04 12:00:00+00'::timestamptz,
  '2026-05-05 12:00:00+00'::timestamptz
);

insert into public.missions (
  mission_date,
  category_key,
  title,
  short_description,
  notice_text,
  is_time_sensitive,
  status,
  valid_from,
  valid_to
) values (
  '2026-05-05'::date,
  'food',
  '특별한 날 먹는 음식',
  '생일, 명절, 축제 때 자주 먹는 음식을 사진으로 보여주세요. 음식 자체가 잘 보이게 찍어주면 좋아요.',
  ''::text,
  false,
  'published',
  '2026-05-05 12:00:00+00'::timestamptz,
  '2026-05-06 12:00:00+00'::timestamptz
);

insert into public.missions (
  mission_date,
  category_key,
  title,
  short_description,
  notice_text,
  is_time_sensitive,
  status,
  valid_from,
  valid_to
) values (
  '2026-05-06'::date,
  'food',
  '편의점 인기 먹거리',
  '현지 편의점에서 사람들이 많이 사는 음식 3가지를 사진으로 보여주세요. 음식 자체가 잘 보이게 찍어주면 좋아요.',
  ''::text,
  false,
  'published',
  '2026-05-06 12:00:00+00'::timestamptz,
  '2026-05-07 12:00:00+00'::timestamptz
);

insert into public.missions (
  mission_date,
  category_key,
  title,
  short_description,
  notice_text,
  is_time_sensitive,
  status,
  valid_from,
  valid_to
) values (
  '2026-05-07'::date,
  'food',
  '매운맛 기준 설명하기',
  '당신의 나라 사람들이 생각하는 ‘매운 음식’을 하나 사진으로 보여주세요. 음식 자체가 잘 보이게 찍어주면 좋아요.',
  ''::text,
  false,
  'published',
  '2026-05-07 12:00:00+00'::timestamptz,
  '2026-05-08 12:00:00+00'::timestamptz
);

insert into public.missions (
  mission_date,
  category_key,
  title,
  short_description,
  notice_text,
  is_time_sensitive,
  status,
  valid_from,
  valid_to
) values (
  '2026-05-08'::date,
  'food',
  '카페 대표 메뉴 소개',
  '카페에서 가장 흔히 주문하는 음료나 디저트를 사진으로 보여주세요. 음식 자체가 잘 보이게 찍어주면 좋아요.',
  ''::text,
  false,
  'published',
  '2026-05-08 12:00:00+00'::timestamptz,
  '2026-05-09 12:00:00+00'::timestamptz
);

insert into public.missions (
  mission_date,
  category_key,
  title,
  short_description,
  notice_text,
  is_time_sensitive,
  status,
  valid_from,
  valid_to
) values (
  '2026-05-09'::date,
  'food',
  '계절 음식 보여주기',
  '지금 계절에만 자주 먹는 음식이나 과일을 사진으로 보여주세요. 음식 자체가 잘 보이게 찍어주면 좋아요.',
  ''::text,
  false,
  'published',
  '2026-05-09 12:00:00+00'::timestamptz,
  '2026-05-10 12:00:00+00'::timestamptz
);

insert into public.missions (
  mission_date,
  category_key,
  title,
  short_description,
  notice_text,
  is_time_sensitive,
  status,
  valid_from,
  valid_to
) values (
  '2026-05-10'::date,
  'food',
  '식사 예절 한 가지',
  '식사할 때 지키는 기본 예절 1가지를 보여주거나 사진으로 보여주고 짧게 설명해주세요. 음식 자체가 잘 보이게 찍어주면 좋아요.',
  ''::text,
  false,
  'published',
  '2026-05-10 12:00:00+00'::timestamptz,
  '2026-05-11 12:00:00+00'::timestamptz
);

insert into public.missions (
  mission_date,
  category_key,
  title,
  short_description,
  notice_text,
  is_time_sensitive,
  status,
  valid_from,
  valid_to
) values (
  '2026-05-11'::date,
  'food',
  '도시락 문화 소개',
  '학교나 회사에서 먹는 도시락 문화를 사진으로 보여주세요. 음식 자체가 잘 보이게 찍어주면 좋아요.',
  ''::text,
  false,
  'published',
  '2026-05-11 12:00:00+00'::timestamptz,
  '2026-05-12 12:00:00+00'::timestamptz
);

insert into public.missions (
  mission_date,
  category_key,
  title,
  short_description,
  notice_text,
  is_time_sensitive,
  status,
  valid_from,
  valid_to
) values (
  '2026-05-12'::date,
  'food',
  '배달 음식 TOP 3',
  '가장 자주 시켜 먹는 배달 음식을 3가지 사진으로 보여주세요. 음식 자체가 잘 보이게 찍어주면 좋아요.',
  ''::text,
  false,
  'published',
  '2026-05-12 12:00:00+00'::timestamptz,
  '2026-05-13 12:00:00+00'::timestamptz
);

insert into public.missions (
  mission_date,
  category_key,
  title,
  short_description,
  notice_text,
  is_time_sensitive,
  status,
  valid_from,
  valid_to
) values (
  '2026-05-13'::date,
  'food',
  '시장 음식 탐방',
  '재래시장이나 로컬 마켓에서 살 수 있는 음식을 사진으로 보여주세요. 음식 자체가 잘 보이게 찍어주면 좋아요.',
  ''::text,
  false,
  'published',
  '2026-05-13 12:00:00+00'::timestamptz,
  '2026-05-14 12:00:00+00'::timestamptz
);

insert into public.missions (
  mission_date,
  category_key,
  title,
  short_description,
  notice_text,
  is_time_sensitive,
  status,
  valid_from,
  valid_to
) values (
  '2026-05-14'::date,
  'food',
  '손으로 먹는 음식',
  '손으로 먹는 것이 자연스러운 음식이 있다면 사진으로 보여주세요. 음식 자체가 잘 보이게 찍어주면 좋아요.',
  ''::text,
  false,
  'published',
  '2026-05-14 12:00:00+00'::timestamptz,
  '2026-05-15 12:00:00+00'::timestamptz
);

insert into public.missions (
  mission_date,
  category_key,
  title,
  short_description,
  notice_text,
  is_time_sensitive,
  status,
  valid_from,
  valid_to
) values (
  '2026-05-15'::date,
  'food',
  '음식과 함께 마시는 음료',
  '식사할 때 가장 흔히 곁들이는 음료를 사진으로 보여주세요. 음식 자체가 잘 보이게 찍어주면 좋아요.',
  ''::text,
  false,
  'published',
  '2026-05-15 12:00:00+00'::timestamptz,
  '2026-05-16 12:00:00+00'::timestamptz
);

insert into public.missions (
  mission_date,
  category_key,
  title,
  short_description,
  notice_text,
  is_time_sensitive,
  status,
  valid_from,
  valid_to
) values (
  '2026-05-16'::date,
  'food',
  '어린 시절 추억의 간식',
  '어릴 때 많이 먹던 국민 간식을 사진으로 보여주세요. 음식 자체가 잘 보이게 찍어주면 좋아요.',
  ''::text,
  false,
  'published',
  '2026-05-16 12:00:00+00'::timestamptz,
  '2026-05-17 12:00:00+00'::timestamptz
);

insert into public.missions (
  mission_date,
  category_key,
  title,
  short_description,
  notice_text,
  is_time_sensitive,
  status,
  valid_from,
  valid_to
) values (
  '2026-05-17'::date,
  'food',
  '외국인이 놀랄 음식 조합',
  '다른 나라 사람에게는 생소할 수 있는 음식 조합을 사진으로 보여주세요. 음식 자체가 잘 보이게 찍어주면 좋아요.',
  ''::text,
  false,
  'published',
  '2026-05-17 12:00:00+00'::timestamptz,
  '2026-05-18 12:00:00+00'::timestamptz
);

insert into public.missions (
  mission_date,
  category_key,
  title,
  short_description,
  notice_text,
  is_time_sensitive,
  status,
  valid_from,
  valid_to
) values (
  '2026-05-18'::date,
  'food',
  '명절 상차림 한 부분',
  '명절이나 축제 때 차리는 음식 한 부분을 사진으로 보여주세요. 음식 자체가 잘 보이게 찍어주면 좋아요.',
  ''::text,
  false,
  'published',
  '2026-05-18 12:00:00+00'::timestamptz,
  '2026-05-19 12:00:00+00'::timestamptz
);

insert into public.missions (
  mission_date,
  category_key,
  title,
  short_description,
  notice_text,
  is_time_sensitive,
  status,
  valid_from,
  valid_to
) values (
  '2026-05-19'::date,
  'food',
  '식당에서 기본으로 나오는 것',
  '식당에 가면 무료로 제공되는 기본 음식이나 서비스가 있나요 사진으로 보여주세요. 음식 자체가 잘 보이게 찍어주면 좋아요.',
  ''::text,
  false,
  'published',
  '2026-05-19 12:00:00+00'::timestamptz,
  '2026-05-20 12:00:00+00'::timestamptz
);

insert into public.missions (
  mission_date,
  category_key,
  title,
  short_description,
  notice_text,
  is_time_sensitive,
  status,
  valid_from,
  valid_to
) values (
  '2026-05-20'::date,
  'food',
  '로컬 소스/양념 소개',
  '현지 사람들이 자주 쓰는 소스나 양념 하나를 사진으로 보여주세요. 음식 자체가 잘 보이게 찍어주면 좋아요.',
  ''::text,
  false,
  'published',
  '2026-05-20 12:00:00+00'::timestamptz,
  '2026-05-21 12:00:00+00'::timestamptz
);

insert into public.missions (
  mission_date,
  category_key,
  title,
  short_description,
  notice_text,
  is_time_sensitive,
  status,
  valid_from,
  valid_to
) values (
  '2026-05-21'::date,
  'food',
  '채식 메뉴 찾기',
  '당신의 동네에서 쉽게 찾을 수 있는 채식 메뉴를 사진으로 보여주세요. 음식 자체가 잘 보이게 찍어주면 좋아요.',
  ''::text,
  false,
  'published',
  '2026-05-21 12:00:00+00'::timestamptz,
  '2026-05-22 12:00:00+00'::timestamptz
);

insert into public.missions (
  mission_date,
  category_key,
  title,
  short_description,
  notice_text,
  is_time_sensitive,
  status,
  valid_from,
  valid_to
) values (
  '2026-05-22'::date,
  'food',
  '야식 문화 보여주기',
  '늦은 밤 사람들이 자주 먹는 음식이 있다면 사진으로 보여주세요. 음식 자체가 잘 보이게 찍어주면 좋아요.',
  ''::text,
  false,
  'published',
  '2026-05-22 12:00:00+00'::timestamptz,
  '2026-05-23 12:00:00+00'::timestamptz
);

insert into public.missions (
  mission_date,
  category_key,
  title,
  short_description,
  notice_text,
  is_time_sensitive,
  status,
  valid_from,
  valid_to
) values (
  '2026-05-23'::date,
  'food',
  '식사 시간 차이 설명',
  '점심이나 저녁을 보통 몇 시에 먹는지 사진으로 보여주세요. 음식 자체가 잘 보이게 찍어주면 좋아요.',
  ''::text,
  false,
  'published',
  '2026-05-23 12:00:00+00'::timestamptz,
  '2026-05-24 12:00:00+00'::timestamptz
);

insert into public.missions (
  mission_date,
  category_key,
  title,
  short_description,
  notice_text,
  is_time_sensitive,
  status,
  valid_from,
  valid_to
) values (
  '2026-05-24'::date,
  'food',
  '지역 대표 빵 소개',
  '빵 문화가 있다면 가장 대중적인 빵 하나를 사진으로 보여주세요. 음식 자체가 잘 보이게 찍어주면 좋아요.',
  ''::text,
  false,
  'published',
  '2026-05-24 12:00:00+00'::timestamptz,
  '2026-05-25 12:00:00+00'::timestamptz
);

insert into public.missions (
  mission_date,
  category_key,
  title,
  short_description,
  notice_text,
  is_time_sensitive,
  status,
  valid_from,
  valid_to
) values (
  '2026-05-25'::date,
  'food',
  '음식 주문 표현 배우기',
  '식당에서 가장 자주 쓰는 주문 표현 한 문장을 알려주세요 사진으로 보여주세요. 음식 자체가 잘 보이게 찍어주면 좋아요.',
  ''::text,
  false,
  'published',
  '2026-05-25 12:00:00+00'::timestamptz,
  '2026-05-26 12:00:00+00'::timestamptz
);

insert into public.missions (
  mission_date,
  category_key,
  title,
  short_description,
  notice_text,
  is_time_sensitive,
  status,
  valid_from,
  valid_to
) values (
  '2026-05-26'::date,
  'food',
  '가장 흔한 해장 음식',
  '숙취 해소용으로 유명한 음식을 사진으로 보여주세요. 음식 자체가 잘 보이게 찍어주면 좋아요.',
  ''::text,
  false,
  'published',
  '2026-05-26 12:00:00+00'::timestamptz,
  '2026-05-27 12:00:00+00'::timestamptz
);

insert into public.missions (
  mission_date,
  category_key,
  title,
  short_description,
  notice_text,
  is_time_sensitive,
  status,
  valid_from,
  valid_to
) values (
  '2026-05-27'::date,
  'food',
  '학교 앞 인기 음식',
  '학생들이 자주 먹는 학교 앞 음식을 사진으로 보여주세요. 음식 자체가 잘 보이게 찍어주면 좋아요.',
  ''::text,
  false,
  'published',
  '2026-05-27 12:00:00+00'::timestamptz,
  '2026-05-28 12:00:00+00'::timestamptz
);

insert into public.missions (
  mission_date,
  category_key,
  title,
  short_description,
  notice_text,
  is_time_sensitive,
  status,
  valid_from,
  valid_to
) values (
  '2026-05-28'::date,
  'food',
  '가족이 좋아하는 집 레시피',
  '가족이 자주 만들어 먹는 간단한 요리 하나를 사진으로 보여주세요. 음식 자체가 잘 보이게 찍어주면 좋아요.',
  ''::text,
  false,
  'published',
  '2026-05-28 12:00:00+00'::timestamptz,
  '2026-05-29 12:00:00+00'::timestamptz
);

insert into public.missions (
  mission_date,
  category_key,
  title,
  short_description,
  notice_text,
  is_time_sensitive,
  status,
  valid_from,
  valid_to
) values (
  '2026-05-29'::date,
  'food',
  '음식 이름의 재미있는 뜻',
  '현지 음식 이름 중 뜻이 재미있는 것이 있다면 사진으로 보여주세요. 음식 자체가 잘 보이게 찍어주면 좋아요.',
  ''::text,
  false,
  'published',
  '2026-05-29 12:00:00+00'::timestamptz,
  '2026-05-30 12:00:00+00'::timestamptz
);

insert into public.missions (
  mission_date,
  category_key,
  title,
  short_description,
  notice_text,
  is_time_sensitive,
  status,
  valid_from,
  valid_to
) values (
  '2026-05-30'::date,
  'food',
  '내 나라를 한 접시로 표현',
  '당신의 나라를 대표한다고 생각하는 음식 한 접시를 사진으로 보여주세요. 음식 자체가 잘 보이게 찍어주면 좋아요.',
  ''::text,
  false,
  'published',
  '2026-05-30 12:00:00+00'::timestamptz,
  '2026-05-31 12:00:00+00'::timestamptz
);

insert into public.missions (
  mission_date,
  category_key,
  title,
  short_description,
  notice_text,
  is_time_sensitive,
  status,
  valid_from,
  valid_to
) values (
  '2026-05-31'::date,
  'daily_life',
  '하루 시작 루틴',
  '아침에 일어나서 가장 먼저 하는 일을 사진으로 보여주세요. 행동 장면이 어렵다면 관련 물건만 찍어도 괜찮아요.',
  ''::text,
  false,
  'published',
  '2026-05-31 12:00:00+00'::timestamptz,
  '2026-06-01 12:00:00+00'::timestamptz
);

insert into public.missions (
  mission_date,
  category_key,
  title,
  short_description,
  notice_text,
  is_time_sensitive,
  status,
  valid_from,
  valid_to
) values (
  '2026-06-01'::date,
  'daily_life',
  '출근/등교 방법 소개',
  '가장 흔한 출근이나 등교 방법을 사진으로 보여주세요. 행동 장면이 어렵다면 관련 물건만 찍어도 괜찮아요.',
  ''::text,
  false,
  'published',
  '2026-06-01 12:00:00+00'::timestamptz,
  '2026-06-02 12:00:00+00'::timestamptz
);

insert into public.missions (
  mission_date,
  category_key,
  title,
  short_description,
  notice_text,
  is_time_sensitive,
  status,
  valid_from,
  valid_to
) values (
  '2026-06-02'::date,
  'daily_life',
  '점심시간 풍경',
  '점심시간에 사람들은 주로 그 장면이나 관련 물건을 사진으로 보여주세요. 행동 장면이 어렵다면 관련 물건만 찍어도 괜찮아요.',
  ''::text,
  false,
  'published',
  '2026-06-02 12:00:00+00'::timestamptz,
  '2026-06-03 12:00:00+00'::timestamptz
);

insert into public.missions (
  mission_date,
  category_key,
  title,
  short_description,
  notice_text,
  is_time_sensitive,
  status,
  valid_from,
  valid_to
) values (
  '2026-06-03'::date,
  'daily_life',
  '퇴근 후 일상',
  '퇴근이나 하교 후 가장 흔한 일상을 사진으로 보여주세요. 행동 장면이 어렵다면 관련 물건만 찍어도 괜찮아요.',
  ''::text,
  false,
  'published',
  '2026-06-03 12:00:00+00'::timestamptz,
  '2026-06-04 12:00:00+00'::timestamptz
);

insert into public.missions (
  mission_date,
  category_key,
  title,
  short_description,
  notice_text,
  is_time_sensitive,
  status,
  valid_from,
  valid_to
) values (
  '2026-06-04'::date,
  'daily_life',
  '주말 오전 보내기',
  '당신의 나라 사람들이 주말 오전을 보내는 방식을 사진으로 보여주세요. 행동 장면이 어렵다면 관련 물건만 찍어도 괜찮아요.',
  ''::text,
  false,
  'published',
  '2026-06-04 12:00:00+00'::timestamptz,
  '2026-06-05 12:00:00+00'::timestamptz
);

insert into public.missions (
  mission_date,
  category_key,
  title,
  short_description,
  notice_text,
  is_time_sensitive,
  status,
  valid_from,
  valid_to
) values (
  '2026-06-05'::date,
  'daily_life',
  '집에서 신발 벗기?',
  '집 안에서 신발을 벗는지, 그대로 신는지 사진으로 보여주세요. 행동 장면이 어렵다면 관련 물건만 찍어도 괜찮아요.',
  ''::text,
  false,
  'published',
  '2026-06-05 12:00:00+00'::timestamptz,
  '2026-06-06 12:00:00+00'::timestamptz
);

insert into public.missions (
  mission_date,
  category_key,
  title,
  short_description,
  notice_text,
  is_time_sensitive,
  status,
  valid_from,
  valid_to
) values (
  '2026-06-06'::date,
  'daily_life',
  '동네 슈퍼 이용법',
  '동네 가게에서 자주 사는 물건과 이용 방식을 사진으로 보여주세요. 행동 장면이 어렵다면 관련 물건만 찍어도 괜찮아요.',
  ''::text,
  false,
  'published',
  '2026-06-06 12:00:00+00'::timestamptz,
  '2026-06-07 12:00:00+00'::timestamptz
);

insert into public.missions (
  mission_date,
  category_key,
  title,
  short_description,
  notice_text,
  is_time_sensitive,
  status,
  valid_from,
  valid_to
) values (
  '2026-06-07'::date,
  'daily_life',
  '줄 서는 문화',
  '줄을 설 때 지켜지는 규칙이나 분위기를 사진으로 보여주세요. 행동 장면이 어렵다면 관련 물건만 찍어도 괜찮아요.',
  ''::text,
  false,
  'published',
  '2026-06-07 12:00:00+00'::timestamptz,
  '2026-06-08 12:00:00+00'::timestamptz
);

insert into public.missions (
  mission_date,
  category_key,
  title,
  short_description,
  notice_text,
  is_time_sensitive,
  status,
  valid_from,
  valid_to
) values (
  '2026-06-08'::date,
  'daily_life',
  '엘리베이터/대중교통 예절',
  '공공장소에서 자연스럽게 지키는 예절 하나를 사진으로 보여주세요. 행동 장면이 어렵다면 관련 물건만 찍어도 괜찮아요.',
  ''::text,
  false,
  'published',
  '2026-06-08 12:00:00+00'::timestamptz,
  '2026-06-09 12:00:00+00'::timestamptz
);

insert into public.missions (
  mission_date,
  category_key,
  title,
  short_description,
  notice_text,
  is_time_sensitive,
  status,
  valid_from,
  valid_to
) values (
  '2026-06-09'::date,
  'daily_life',
  '비 오는 날 일상',
  '비가 오는 날 사람들이 흔히 하는 행동을 사진으로 보여주세요. 행동 장면이 어렵다면 관련 물건만 찍어도 괜찮아요.',
  ''::text,
  false,
  'published',
  '2026-06-09 12:00:00+00'::timestamptz,
  '2026-06-10 12:00:00+00'::timestamptz
);

insert into public.missions (
  mission_date,
  category_key,
  title,
  short_description,
  notice_text,
  is_time_sensitive,
  status,
  valid_from,
  valid_to
) values (
  '2026-06-10'::date,
  'daily_life',
  '쓰레기 버리는 규칙',
  '쓰레기 분리배출이나 버리는 방식을 간단히 사진으로 보여주고 짧게 설명해주세요. 행동 장면이 어렵다면 관련 물건만 찍어도 괜찮아요.',
  ''::text,
  false,
  'published',
  '2026-06-10 12:00:00+00'::timestamptz,
  '2026-06-11 12:00:00+00'::timestamptz
);

insert into public.missions (
  mission_date,
  category_key,
  title,
  short_description,
  notice_text,
  is_time_sensitive,
  status,
  valid_from,
  valid_to
) values (
  '2026-06-11'::date,
  'daily_life',
  '친구와 약속 잡는 방식',
  '친구를 만날 때 보통 얼마나 미리 약속을 잡나요 사진으로 보여주세요. 행동 장면이 어렵다면 관련 물건만 찍어도 괜찮아요.',
  ''::text,
  false,
  'published',
  '2026-06-11 12:00:00+00'::timestamptz,
  '2026-06-12 12:00:00+00'::timestamptz
);

insert into public.missions (
  mission_date,
  category_key,
  title,
  short_description,
  notice_text,
  is_time_sensitive,
  status,
  valid_from,
  valid_to
) values (
  '2026-06-12'::date,
  'daily_life',
  '동네 소음의 기준',
  '당신이 사는 곳에서 ‘시끄럽다’고 느끼는 기준을 사진으로 보여주고 짧게 설명해주세요. 행동 장면이 어렵다면 관련 물건만 찍어도 괜찮아요.',
  ''::text,
  false,
  'published',
  '2026-06-12 12:00:00+00'::timestamptz,
  '2026-06-13 12:00:00+00'::timestamptz
);

insert into public.missions (
  mission_date,
  category_key,
  title,
  short_description,
  notice_text,
  is_time_sensitive,
  status,
  valid_from,
  valid_to
) values (
  '2026-06-13'::date,
  'daily_life',
  '가장 흔한 인사 타이밍',
  '언제 인사를 하는지, 어떤 상황에서 생략하는지 사진으로 보여주세요. 행동 장면이 어렵다면 관련 물건만 찍어도 괜찮아요.',
  ''::text,
  false,
  'published',
  '2026-06-13 12:00:00+00'::timestamptz,
  '2026-06-14 12:00:00+00'::timestamptz
);

insert into public.missions (
  mission_date,
  category_key,
  title,
  short_description,
  notice_text,
  is_time_sensitive,
  status,
  valid_from,
  valid_to
) values (
  '2026-06-14'::date,
  'daily_life',
  '저녁 가족 시간',
  '저녁 시간에 가족이 함께 보내는 방식이 있나요 사진으로 보여주세요. 행동 장면이 어렵다면 관련 물건만 찍어도 괜찮아요.',
  ''::text,
  false,
  'published',
  '2026-06-14 12:00:00+00'::timestamptz,
  '2026-06-15 12:00:00+00'::timestamptz
);

insert into public.missions (
  mission_date,
  category_key,
  title,
  short_description,
  notice_text,
  is_time_sensitive,
  status,
  valid_from,
  valid_to
) values (
  '2026-06-15'::date,
  'daily_life',
  '빨래/청소 루틴',
  '집안일을 보통 언제 어떻게 하는지 사진으로 보여주세요. 행동 장면이 어렵다면 관련 물건만 찍어도 괜찮아요.',
  ''::text,
  false,
  'published',
  '2026-06-15 12:00:00+00'::timestamptz,
  '2026-06-16 12:00:00+00'::timestamptz
);

insert into public.missions (
  mission_date,
  category_key,
  title,
  short_description,
  notice_text,
  is_time_sensitive,
  status,
  valid_from,
  valid_to
) values (
  '2026-06-16'::date,
  'daily_life',
  '동네 공원 활용법',
  '사람들이 공원을 어떻게 이용하는지 사진으로 보여주세요. 행동 장면이 어렵다면 관련 물건만 찍어도 괜찮아요.',
  ''::text,
  false,
  'published',
  '2026-06-16 12:00:00+00'::timestamptz,
  '2026-06-17 12:00:00+00'::timestamptz
);

insert into public.missions (
  mission_date,
  category_key,
  title,
  short_description,
  notice_text,
  is_time_sensitive,
  status,
  valid_from,
  valid_to
) values (
  '2026-06-17'::date,
  'daily_life',
  '편의시설 한 바퀴',
  '집 근처에서 5분 안에 갈 수 있는 생활 편의시설을 사진으로 보여주세요. 행동 장면이 어렵다면 관련 물건만 찍어도 괜찮아요.',
  ''::text,
  false,
  'published',
  '2026-06-17 12:00:00+00'::timestamptz,
  '2026-06-18 12:00:00+00'::timestamptz
);

insert into public.missions (
  mission_date,
  category_key,
  title,
  short_description,
  notice_text,
  is_time_sensitive,
  status,
  valid_from,
  valid_to
) values (
  '2026-06-18'::date,
  'daily_life',
  '현지의 ‘바쁜 하루’',
  '당신의 나라에서 바쁜 하루는 어떤 모습인지 사진으로 보여주고 짧게 설명해주세요. 행동 장면이 어렵다면 관련 물건만 찍어도 괜찮아요.',
  ''::text,
  false,
  'published',
  '2026-06-18 12:00:00+00'::timestamptz,
  '2026-06-19 12:00:00+00'::timestamptz
);

insert into public.missions (
  mission_date,
  category_key,
  title,
  short_description,
  notice_text,
  is_time_sensitive,
  status,
  valid_from,
  valid_to
) values (
  '2026-06-19'::date,
  'daily_life',
  '휴대폰 없이 기다리기?',
  '기다리는 시간에 사람들은 주로 그 장면이나 관련 물건을 사진으로 보여주세요. 행동 장면이 어렵다면 관련 물건만 찍어도 괜찮아요.',
  ''::text,
  false,
  'published',
  '2026-06-19 12:00:00+00'::timestamptz,
  '2026-06-20 12:00:00+00'::timestamptz
);

insert into public.missions (
  mission_date,
  category_key,
  title,
  short_description,
  notice_text,
  is_time_sensitive,
  status,
  valid_from,
  valid_to
) values (
  '2026-06-20'::date,
  'daily_life',
  '동네 주민과의 거리감',
  '이웃과 어느 정도 친하게 지내는지 사진으로 보여주고 짧게 설명해주세요. 행동 장면이 어렵다면 관련 물건만 찍어도 괜찮아요.',
  ''::text,
  false,
  'published',
  '2026-06-20 12:00:00+00'::timestamptz,
  '2026-06-21 12:00:00+00'::timestamptz
);

insert into public.missions (
  mission_date,
  category_key,
  title,
  short_description,
  notice_text,
  is_time_sensitive,
  status,
  valid_from,
  valid_to
) values (
  '2026-06-21'::date,
  'daily_life',
  '평일 저녁 혼밥/함께 식사',
  '평일 저녁을 혼자 먹는지 함께 먹는지 사진으로 보여주세요. 행동 장면이 어렵다면 관련 물건만 찍어도 괜찮아요.',
  ''::text,
  false,
  'published',
  '2026-06-21 12:00:00+00'::timestamptz,
  '2026-06-22 12:00:00+00'::timestamptz
);

insert into public.missions (
  mission_date,
  category_key,
  title,
  short_description,
  notice_text,
  is_time_sensitive,
  status,
  valid_from,
  valid_to
) values (
  '2026-06-22'::date,
  'daily_life',
  '가장 자주 쓰는 메신저 대화',
  '친구와 자주 주고받는 짧은 표현을 하나 사진으로 보여주세요. 행동 장면이 어렵다면 관련 물건만 찍어도 괜찮아요.',
  ''::text,
  false,
  'published',
  '2026-06-22 12:00:00+00'::timestamptz,
  '2026-06-23 12:00:00+00'::timestamptz
);

insert into public.missions (
  mission_date,
  category_key,
  title,
  short_description,
  notice_text,
  is_time_sensitive,
  status,
  valid_from,
  valid_to
) values (
  '2026-06-23'::date,
  'daily_life',
  '대중교통에서 하는 일',
  '버스나 지하철에서 사람들은 주로 그 장면이나 관련 물건을 사진으로 보여주세요. 행동 장면이 어렵다면 관련 물건만 찍어도 괜찮아요.',
  ''::text,
  false,
  'published',
  '2026-06-23 12:00:00+00'::timestamptz,
  '2026-06-24 12:00:00+00'::timestamptz
);

insert into public.missions (
  mission_date,
  category_key,
  title,
  short_description,
  notice_text,
  is_time_sensitive,
  status,
  valid_from,
  valid_to
) values (
  '2026-06-24'::date,
  'daily_life',
  '현지의 작은 친절',
  '일상에서 자주 보는 작은 배려 행동을 사진으로 보여주세요. 행동 장면이 어렵다면 관련 물건만 찍어도 괜찮아요.',
  ''::text,
  false,
  'published',
  '2026-06-24 12:00:00+00'::timestamptz,
  '2026-06-25 12:00:00+00'::timestamptz
);

insert into public.missions (
  mission_date,
  category_key,
  title,
  short_description,
  notice_text,
  is_time_sensitive,
  status,
  valid_from,
  valid_to
) values (
  '2026-06-25'::date,
  'daily_life',
  '카페/식당 자리 맡기 문화',
  '가방이나 물건으로 자리를 맡는 문화가 있나요 사진으로 보여주세요. 행동 장면이 어렵다면 관련 물건만 찍어도 괜찮아요.',
  ''::text,
  false,
  'published',
  '2026-06-25 12:00:00+00'::timestamptz,
  '2026-06-26 12:00:00+00'::timestamptz
);

insert into public.missions (
  mission_date,
  category_key,
  title,
  short_description,
  notice_text,
  is_time_sensitive,
  status,
  valid_from,
  valid_to
) values (
  '2026-06-26'::date,
  'daily_life',
  '실내 온도 취향',
  '실내를 덥게/시원하게 유지하는 편인지 사진으로 보여주세요. 행동 장면이 어렵다면 관련 물건만 찍어도 괜찮아요.',
  ''::text,
  false,
  'published',
  '2026-06-26 12:00:00+00'::timestamptz,
  '2026-06-27 12:00:00+00'::timestamptz
);

insert into public.missions (
  mission_date,
  category_key,
  title,
  short_description,
  notice_text,
  is_time_sensitive,
  status,
  valid_from,
  valid_to
) values (
  '2026-06-27'::date,
  'daily_life',
  '현지의 시간 감각',
  '약속 시간 5분 전/정시/조금 늦는 것에 대한 인식을 사진으로 보여주고 짧게 설명해주세요. 행동 장면이 어렵다면 관련 물건만 찍어도 괜찮아요.',
  ''::text,
  false,
  'published',
  '2026-06-27 12:00:00+00'::timestamptz,
  '2026-06-28 12:00:00+00'::timestamptz
);

insert into public.missions (
  mission_date,
  category_key,
  title,
  short_description,
  notice_text,
  is_time_sensitive,
  status,
  valid_from,
  valid_to
) values (
  '2026-06-28'::date,
  'daily_life',
  '평범한 하루 사진 3컷',
  '아주 평범한 하루를 사진 3장으로 표현해보세요. 행동 장면이 어렵다면 관련 물건만 찍어도 괜찮아요.',
  ''::text,
  false,
  'published',
  '2026-06-28 12:00:00+00'::timestamptz,
  '2026-06-29 12:00:00+00'::timestamptz
);

insert into public.missions (
  mission_date,
  category_key,
  title,
  short_description,
  notice_text,
  is_time_sensitive,
  status,
  valid_from,
  valid_to
) values (
  '2026-06-29'::date,
  'daily_life',
  '우리 나라의 ‘당연한 것’',
  '당신에겐 당연하지만 외국인에게는 낯설 수 있는 일상 습관을 사진으로 보여주세요. 행동 장면이 어렵다면 관련 물건만 찍어도 괜찮아요.',
  ''::text,
  false,
  'published',
  '2026-06-29 12:00:00+00'::timestamptz,
  '2026-06-30 12:00:00+00'::timestamptz
);

insert into public.missions (
  mission_date,
  category_key,
  title,
  short_description,
  notice_text,
  is_time_sensitive,
  status,
  valid_from,
  valid_to
) values (
  '2026-06-30'::date,
  'place',
  '내 동네 대표 장소',
  '당신이 사는 곳을 가장 잘 보여주는 장소 하나를 사진으로 보여주세요. 장소 분위기가 드러나게 전경이나 입구를 찍어도 좋아요.',
  ''::text,
  false,
  'published',
  '2026-06-30 12:00:00+00'::timestamptz,
  '2026-07-01 12:00:00+00'::timestamptz
);

insert into public.missions (
  mission_date,
  category_key,
  title,
  short_description,
  notice_text,
  is_time_sensitive,
  status,
  valid_from,
  valid_to
) values (
  '2026-07-01'::date,
  'place',
  '가장 자주 가는 가게',
  '가장 자주 가는 가게와 그 이유를 사진으로 보여주세요. 장소 분위기가 드러나게 전경이나 입구를 찍어도 좋아요.',
  ''::text,
  false,
  'published',
  '2026-07-01 12:00:00+00'::timestamptz,
  '2026-07-02 12:00:00+00'::timestamptz
);

insert into public.missions (
  mission_date,
  category_key,
  title,
  short_description,
  notice_text,
  is_time_sensitive,
  status,
  valid_from,
  valid_to
) values (
  '2026-07-02'::date,
  'place',
  '현지 시장 풍경',
  '시장이나 장터의 분위기를 사진으로 보여주세요. 장소 분위기가 드러나게 전경이나 입구를 찍어도 좋아요.',
  ''::text,
  false,
  'published',
  '2026-07-02 12:00:00+00'::timestamptz,
  '2026-07-03 12:00:00+00'::timestamptz
);

insert into public.missions (
  mission_date,
  category_key,
  title,
  short_description,
  notice_text,
  is_time_sensitive,
  status,
  valid_from,
  valid_to
) values (
  '2026-07-03'::date,
  'place',
  '도서관/서점 탐방',
  '사람들이 공부하거나 쉬는 공간을 사진으로 보여주세요. 장소 분위기가 드러나게 전경이나 입구를 찍어도 좋아요.',
  ''::text,
  false,
  'published',
  '2026-07-03 12:00:00+00'::timestamptz,
  '2026-07-04 12:00:00+00'::timestamptz
);

insert into public.missions (
  mission_date,
  category_key,
  title,
  short_description,
  notice_text,
  is_time_sensitive,
  status,
  valid_from,
  valid_to
) values (
  '2026-07-04'::date,
  'place',
  '공원에서 보이는 사람들',
  '공원에서 사람들이 무엇을 하는지 사진으로 보여주세요. 장소 분위기가 드러나게 전경이나 입구를 찍어도 좋아요.',
  ''::text,
  false,
  'published',
  '2026-07-04 12:00:00+00'::timestamptz,
  '2026-07-05 12:00:00+00'::timestamptz
);

insert into public.missions (
  mission_date,
  category_key,
  title,
  short_description,
  notice_text,
  is_time_sensitive,
  status,
  valid_from,
  valid_to
) values (
  '2026-07-05'::date,
  'place',
  '버스정류장 또는 지하철역',
  '대중교통 공간의 분위기와 특징을 사진으로 보여주세요. 장소 분위기가 드러나게 전경이나 입구를 찍어도 좋아요.',
  ''::text,
  false,
  'published',
  '2026-07-05 12:00:00+00'::timestamptz,
  '2026-07-06 12:00:00+00'::timestamptz
);

insert into public.missions (
  mission_date,
  category_key,
  title,
  short_description,
  notice_text,
  is_time_sensitive,
  status,
  valid_from,
  valid_to
) values (
  '2026-07-06'::date,
  'place',
  '동네 카페 vs 로컬 찻집',
  '현지에서 흔한 휴식 공간을 하나 사진으로 보여주세요. 장소 분위기가 드러나게 전경이나 입구를 찍어도 좋아요.',
  ''::text,
  false,
  'published',
  '2026-07-06 12:00:00+00'::timestamptz,
  '2026-07-07 12:00:00+00'::timestamptz
);

insert into public.missions (
  mission_date,
  category_key,
  title,
  short_description,
  notice_text,
  is_time_sensitive,
  status,
  valid_from,
  valid_to
) values (
  '2026-07-07'::date,
  'place',
  '사진 명소보다 로컬 명소',
  '관광지가 아닌 현지인 추천 장소를 사진으로 보여주세요. 장소 분위기가 드러나게 전경이나 입구를 찍어도 좋아요.',
  ''::text,
  false,
  'published',
  '2026-07-07 12:00:00+00'::timestamptz,
  '2026-07-08 12:00:00+00'::timestamptz
);

insert into public.missions (
  mission_date,
  category_key,
  title,
  short_description,
  notice_text,
  is_time_sensitive,
  status,
  valid_from,
  valid_to
) values (
  '2026-07-08'::date,
  'place',
  '야경이 좋은 곳',
  '밤에 가면 분위기가 달라지는 장소를 사진으로 보여주세요. 장소 분위기가 드러나게 전경이나 입구를 찍어도 좋아요.',
  ''::text,
  false,
  'published',
  '2026-07-08 12:00:00+00'::timestamptz,
  '2026-07-09 12:00:00+00'::timestamptz
);

insert into public.missions (
  mission_date,
  category_key,
  title,
  short_description,
  notice_text,
  is_time_sensitive,
  status,
  valid_from,
  valid_to
) values (
  '2026-07-09'::date,
  'place',
  '아이들이 많이 가는 장소',
  '가족이나 아이들이 자주 찾는 장소를 사진으로 보여주세요. 장소 분위기가 드러나게 전경이나 입구를 찍어도 좋아요.',
  ''::text,
  false,
  'published',
  '2026-07-09 12:00:00+00'::timestamptz,
  '2026-07-10 12:00:00+00'::timestamptz
);

insert into public.missions (
  mission_date,
  category_key,
  title,
  short_description,
  notice_text,
  is_time_sensitive,
  status,
  valid_from,
  valid_to
) values (
  '2026-07-10'::date,
  'place',
  '노인들이 자주 모이는 장소',
  '어르신들이 자주 머무는 장소를 사진으로 보여주세요. 장소 분위기가 드러나게 전경이나 입구를 찍어도 좋아요.',
  ''::text,
  false,
  'published',
  '2026-07-10 12:00:00+00'::timestamptz,
  '2026-07-11 12:00:00+00'::timestamptz
);

insert into public.missions (
  mission_date,
  category_key,
  title,
  short_description,
  notice_text,
  is_time_sensitive,
  status,
  valid_from,
  valid_to
) values (
  '2026-07-11'::date,
  'place',
  '비 오는 날 가기 좋은 곳',
  '날씨가 안 좋을 때 현지 사람들이 자주 가는 장소를 사진으로 보여주세요. 장소 분위기가 드러나게 전경이나 입구를 찍어도 좋아요.',
  ''::text,
  false,
  'published',
  '2026-07-11 12:00:00+00'::timestamptz,
  '2026-07-12 12:00:00+00'::timestamptz
);

insert into public.missions (
  mission_date,
  category_key,
  title,
  short_description,
  notice_text,
  is_time_sensitive,
  status,
  valid_from,
  valid_to
) values (
  '2026-07-12'::date,
  'place',
  '무료로 즐기는 장소',
  '돈을 쓰지 않고도 시간을 보낼 수 있는 장소를 사진으로 보여주세요. 장소 분위기가 드러나게 전경이나 입구를 찍어도 좋아요.',
  ''::text,
  false,
  'published',
  '2026-07-12 12:00:00+00'::timestamptz,
  '2026-07-13 12:00:00+00'::timestamptz
);

insert into public.missions (
  mission_date,
  category_key,
  title,
  short_description,
  notice_text,
  is_time_sensitive,
  status,
  valid_from,
  valid_to
) values (
  '2026-07-13'::date,
  'place',
  '동네 종교/명상 공간',
  '지역 사람들의 마음이 머무는 장소를 사진으로 보여주세요. 장소 분위기가 드러나게 전경이나 입구를 찍어도 좋아요.',
  ''::text,
  false,
  'published',
  '2026-07-13 12:00:00+00'::timestamptz,
  '2026-07-14 12:00:00+00'::timestamptz
);

insert into public.missions (
  mission_date,
  category_key,
  title,
  short_description,
  notice_text,
  is_time_sensitive,
  status,
  valid_from,
  valid_to
) values (
  '2026-07-14'::date,
  'place',
  '현지 스포츠 공간',
  '운동장, 체육관, 공원 등 운동하는 장소를 사진으로 보여주세요. 장소 분위기가 드러나게 전경이나 입구를 찍어도 좋아요.',
  ''::text,
  false,
  'published',
  '2026-07-14 12:00:00+00'::timestamptz,
  '2026-07-15 12:00:00+00'::timestamptz
);

insert into public.missions (
  mission_date,
  category_key,
  title,
  short_description,
  notice_text,
  is_time_sensitive,
  status,
  valid_from,
  valid_to
) values (
  '2026-07-15'::date,
  'place',
  '기념일에 가는 장소',
  '생일이나 데이트, 특별한 날 자주 가는 장소를 사진으로 보여주세요. 장소 분위기가 드러나게 전경이나 입구를 찍어도 좋아요.',
  ''::text,
  false,
  'published',
  '2026-07-15 12:00:00+00'::timestamptz,
  '2026-07-16 12:00:00+00'::timestamptz
);

insert into public.missions (
  mission_date,
  category_key,
  title,
  short_description,
  notice_text,
  is_time_sensitive,
  status,
  valid_from,
  valid_to
) values (
  '2026-07-16'::date,
  'place',
  '출근길 풍경 포인트',
  '출근길/등굣길에서 가장 자주 보는 풍경을 사진으로 보여주세요. 장소 분위기가 드러나게 전경이나 입구를 찍어도 좋아요.',
  ''::text,
  false,
  'published',
  '2026-07-16 12:00:00+00'::timestamptz,
  '2026-07-17 12:00:00+00'::timestamptz
);

insert into public.missions (
  mission_date,
  category_key,
  title,
  short_description,
  notice_text,
  is_time_sensitive,
  status,
  valid_from,
  valid_to
) values (
  '2026-07-17'::date,
  'place',
  '사람이 붐비는 시간',
  '같은 장소가 시간대마다 어떻게 달라지는지 사진으로 보여주고 짧게 설명해주세요. 장소 분위기가 드러나게 전경이나 입구를 찍어도 좋아요.',
  ''::text,
  false,
  'published',
  '2026-07-17 12:00:00+00'::timestamptz,
  '2026-07-18 12:00:00+00'::timestamptz
);

insert into public.missions (
  mission_date,
  category_key,
  title,
  short_description,
  notice_text,
  is_time_sensitive,
  status,
  valid_from,
  valid_to
) values (
  '2026-07-18'::date,
  'place',
  '조용히 쉬는 나만의 장소',
  '혼자 있고 싶을 때 가는 장소를 사진으로 보여주세요. 장소 분위기가 드러나게 전경이나 입구를 찍어도 좋아요.',
  ''::text,
  false,
  'published',
  '2026-07-18 12:00:00+00'::timestamptz,
  '2026-07-19 12:00:00+00'::timestamptz
);

insert into public.missions (
  mission_date,
  category_key,
  title,
  short_description,
  notice_text,
  is_time_sensitive,
  status,
  valid_from,
  valid_to
) values (
  '2026-07-19'::date,
  'place',
  '현지의 포토부스/사진 공간',
  '사진을 찍는 문화가 보이는 장소가 있다면 사진으로 보여주세요. 장소 분위기가 드러나게 전경이나 입구를 찍어도 좋아요.',
  ''::text,
  false,
  'published',
  '2026-07-19 12:00:00+00'::timestamptz,
  '2026-07-20 12:00:00+00'::timestamptz
);

insert into public.missions (
  mission_date,
  category_key,
  title,
  short_description,
  notice_text,
  is_time_sensitive,
  status,
  valid_from,
  valid_to
) values (
  '2026-07-20'::date,
  'place',
  '학생들이 모이는 장소',
  '학생들이 많이 모이는 장소와 분위기를 사진으로 보여주세요. 장소 분위기가 드러나게 전경이나 입구를 찍어도 좋아요.',
  ''::text,
  false,
  'published',
  '2026-07-20 12:00:00+00'::timestamptz,
  '2026-07-21 12:00:00+00'::timestamptz
);

insert into public.missions (
  mission_date,
  category_key,
  title,
  short_description,
  notice_text,
  is_time_sensitive,
  status,
  valid_from,
  valid_to
) values (
  '2026-07-21'::date,
  'place',
  '반려동물과 가는 장소',
  '반려동물과 함께 갈 수 있는 공간이 있다면 사진으로 보여주세요. 장소 분위기가 드러나게 전경이나 입구를 찍어도 좋아요.',
  ''::text,
  false,
  'published',
  '2026-07-21 12:00:00+00'::timestamptz,
  '2026-07-22 12:00:00+00'::timestamptz
);

insert into public.missions (
  mission_date,
  category_key,
  title,
  short_description,
  notice_text,
  is_time_sensitive,
  status,
  valid_from,
  valid_to
) values (
  '2026-07-22'::date,
  'place',
  '전통이 느껴지는 거리',
  '전통 건물이나 오래된 분위기가 남아 있는 장소를 사진으로 보여주세요. 장소 분위기가 드러나게 전경이나 입구를 찍어도 좋아요.',
  ''::text,
  false,
  'published',
  '2026-07-22 12:00:00+00'::timestamptz,
  '2026-07-23 12:00:00+00'::timestamptz
);

insert into public.missions (
  mission_date,
  category_key,
  title,
  short_description,
  notice_text,
  is_time_sensitive,
  status,
  valid_from,
  valid_to
) values (
  '2026-07-23'::date,
  'place',
  '새로 생긴 핫플레이스',
  '요즘 사람들에게 인기 있는 새 장소를 사진으로 보여주세요. 장소 분위기가 드러나게 전경이나 입구를 찍어도 좋아요.',
  ''::text,
  false,
  'published',
  '2026-07-23 12:00:00+00'::timestamptz,
  '2026-07-24 12:00:00+00'::timestamptz
);

insert into public.missions (
  mission_date,
  category_key,
  title,
  short_description,
  notice_text,
  is_time_sensitive,
  status,
  valid_from,
  valid_to
) values (
  '2026-07-24'::date,
  'place',
  '밤에도 안전한가?',
  '밤에 걷기 안전하다고 느끼는 장소를 소개하며 이유를 말해주세요 사진으로 보여주세요. 장소 분위기가 드러나게 전경이나 입구를 찍어도 좋아요.',
  ''::text,
  false,
  'published',
  '2026-07-24 12:00:00+00'::timestamptz,
  '2026-07-25 12:00:00+00'::timestamptz
);

insert into public.missions (
  mission_date,
  category_key,
  title,
  short_description,
  notice_text,
  is_time_sensitive,
  status,
  valid_from,
  valid_to
) values (
  '2026-07-25'::date,
  'place',
  '현지의 대기 공간',
  '병원, 은행, 관공서 등 기다리는 공간의 분위기를 사진으로 보여주세요. 장소 분위기가 드러나게 전경이나 입구를 찍어도 좋아요.',
  ''::text,
  false,
  'published',
  '2026-07-25 12:00:00+00'::timestamptz,
  '2026-07-26 12:00:00+00'::timestamptz
);

insert into public.missions (
  mission_date,
  category_key,
  title,
  short_description,
  notice_text,
  is_time_sensitive,
  status,
  valid_from,
  valid_to
) values (
  '2026-07-26'::date,
  'place',
  '가장 조용한 장소',
  '도시/마을에서 가장 조용하다고 느끼는 장소를 사진으로 보여주세요. 장소 분위기가 드러나게 전경이나 입구를 찍어도 좋아요.',
  ''::text,
  false,
  'published',
  '2026-07-26 12:00:00+00'::timestamptz,
  '2026-07-27 12:00:00+00'::timestamptz
);

insert into public.missions (
  mission_date,
  category_key,
  title,
  short_description,
  notice_text,
  is_time_sensitive,
  status,
  valid_from,
  valid_to
) values (
  '2026-07-27'::date,
  'place',
  '가장 시끄러운 장소',
  '사람들의 에너지가 가장 느껴지는 장소를 사진으로 보여주세요. 장소 분위기가 드러나게 전경이나 입구를 찍어도 좋아요.',
  ''::text,
  false,
  'published',
  '2026-07-27 12:00:00+00'::timestamptz,
  '2026-07-28 12:00:00+00'::timestamptz
);

insert into public.missions (
  mission_date,
  category_key,
  title,
  short_description,
  notice_text,
  is_time_sensitive,
  status,
  valid_from,
  valid_to
) values (
  '2026-07-28'::date,
  'place',
  '내 나라를 느낄 수 있는 거리',
  '이 거리 하나로 당신 나라 분위기를 설명할 수 있는 곳을 사진으로 보여주세요. 장소 분위기가 드러나게 전경이나 입구를 찍어도 좋아요.',
  ''::text,
  false,
  'published',
  '2026-07-28 12:00:00+00'::timestamptz,
  '2026-07-29 12:00:00+00'::timestamptz
);

insert into public.missions (
  mission_date,
  category_key,
  title,
  short_description,
  notice_text,
  is_time_sensitive,
  status,
  valid_from,
  valid_to
) values (
  '2026-07-29'::date,
  'place',
  '장소 하나, 규칙 하나',
  '그 장소에서 꼭 지켜야 하는 규칙이나 매너를 함께 사진으로 보여주세요. 장소 분위기가 드러나게 전경이나 입구를 찍어도 좋아요.',
  ''::text,
  false,
  'published',
  '2026-07-29 12:00:00+00'::timestamptz,
  '2026-07-30 12:00:00+00'::timestamptz
);

insert into public.missions (
  mission_date,
  category_key,
  title,
  short_description,
  notice_text,
  is_time_sensitive,
  status,
  valid_from,
  valid_to
) values (
  '2026-07-30'::date,
  'emotion',
  '기쁠 때 하는 표현',
  '당신의 나라에서 기쁠 때 자주 쓰는 말이나 제스처를 사진으로 보여주세요. 얼굴이 아니어도 괜찮고, 그 감정을 떠올리게 하는 장면이나 물건으로 표현해도 좋아요.',
  ''::text,
  false,
  'published',
  '2026-07-30 12:00:00+00'::timestamptz,
  '2026-07-31 12:00:00+00'::timestamptz
);

insert into public.missions (
  mission_date,
  category_key,
  title,
  short_description,
  notice_text,
  is_time_sensitive,
  status,
  valid_from,
  valid_to
) values (
  '2026-07-31'::date,
  'emotion',
  '당황했을 때 반응',
  '민망하거나 당황할 때 흔히 하는 반응을 사진으로 보여주세요. 얼굴이 아니어도 괜찮고, 그 감정을 떠올리게 하는 장면이나 물건으로 표현해도 좋아요.',
  ''::text,
  false,
  'published',
  '2026-07-31 12:00:00+00'::timestamptz,
  '2026-08-01 12:00:00+00'::timestamptz
);

insert into public.missions (
  mission_date,
  category_key,
  title,
  short_description,
  notice_text,
  is_time_sensitive,
  status,
  valid_from,
  valid_to
) values (
  '2026-08-01'::date,
  'emotion',
  '감사 표현 한 가지',
  '감사할 때 자주 쓰는 말, 행동, 작은 선물을 사진으로 보여주세요. 얼굴이 아니어도 괜찮고, 그 감정을 떠올리게 하는 장면이나 물건으로 표현해도 좋아요.',
  ''::text,
  false,
  'published',
  '2026-08-01 12:00:00+00'::timestamptz,
  '2026-08-02 12:00:00+00'::timestamptz
);

insert into public.missions (
  mission_date,
  category_key,
  title,
  short_description,
  notice_text,
  is_time_sensitive,
  status,
  valid_from,
  valid_to
) values (
  '2026-08-02'::date,
  'emotion',
  '미안할 때의 태도',
  '사과할 때 중요한 요소가 무엇인지 사진으로 보여주고 짧게 설명해주세요. 얼굴이 아니어도 괜찮고, 그 감정을 떠올리게 하는 장면이나 물건으로 표현해도 좋아요.',
  ''::text,
  false,
  'published',
  '2026-08-02 12:00:00+00'::timestamptz,
  '2026-08-03 12:00:00+00'::timestamptz
);

insert into public.missions (
  mission_date,
  category_key,
  title,
  short_description,
  notice_text,
  is_time_sensitive,
  status,
  valid_from,
  valid_to
) values (
  '2026-08-03'::date,
  'emotion',
  '사랑/호감 표현',
  '호감을 표현할 때 직접적인지 간접적인지 사진으로 보여주세요. 얼굴이 아니어도 괜찮고, 그 감정을 떠올리게 하는 장면이나 물건으로 표현해도 좋아요.',
  ''::text,
  false,
  'published',
  '2026-08-03 12:00:00+00'::timestamptz,
  '2026-08-04 12:00:00+00'::timestamptz
);

insert into public.missions (
  mission_date,
  category_key,
  title,
  short_description,
  notice_text,
  is_time_sensitive,
  status,
  valid_from,
  valid_to
) values (
  '2026-08-04'::date,
  'emotion',
  '슬플 때 위로하는 법',
  '슬픈 사람을 어떻게 위로하는지 사진으로 보여주세요. 얼굴이 아니어도 괜찮고, 그 감정을 떠올리게 하는 장면이나 물건으로 표현해도 좋아요.',
  ''::text,
  false,
  'published',
  '2026-08-04 12:00:00+00'::timestamptz,
  '2026-08-05 12:00:00+00'::timestamptz
);

insert into public.missions (
  mission_date,
  category_key,
  title,
  short_description,
  notice_text,
  is_time_sensitive,
  status,
  valid_from,
  valid_to
) values (
  '2026-08-05'::date,
  'emotion',
  '화가 났을 때 보통 어떻게 하나요?',
  '화를 낼 때 직접 말하는지 참는지 사진으로 보여주고 짧게 설명해주세요. 얼굴이 아니어도 괜찮고, 그 감정을 떠올리게 하는 장면이나 물건으로 표현해도 좋아요.',
  ''::text,
  false,
  'published',
  '2026-08-05 12:00:00+00'::timestamptz,
  '2026-08-06 12:00:00+00'::timestamptz
);

insert into public.missions (
  mission_date,
  category_key,
  title,
  short_description,
  notice_text,
  is_time_sensitive,
  status,
  valid_from,
  valid_to
) values (
  '2026-08-06'::date,
  'emotion',
  '칭찬받았을 때 반응',
  '칭찬을 들으면 바로 고맙다고 하는지, 겸손하게 반응하는지 사진으로 보여주세요. 얼굴이 아니어도 괜찮고, 그 감정을 떠올리게 하는 장면이나 물건으로 표현해도 좋아요.',
  ''::text,
  false,
  'published',
  '2026-08-06 12:00:00+00'::timestamptz,
  '2026-08-07 12:00:00+00'::timestamptz
);

insert into public.missions (
  mission_date,
  category_key,
  title,
  short_description,
  notice_text,
  is_time_sensitive,
  status,
  valid_from,
  valid_to
) values (
  '2026-08-07'::date,
  'emotion',
  '긴장할 때 습관',
  '시험이나 발표 전에 자주 하는 행동이 있나요 사진으로 보여주세요. 얼굴이 아니어도 괜찮고, 그 감정을 떠올리게 하는 장면이나 물건으로 표현해도 좋아요.',
  ''::text,
  false,
  'published',
  '2026-08-07 12:00:00+00'::timestamptz,
  '2026-08-08 12:00:00+00'::timestamptz
);

insert into public.missions (
  mission_date,
  category_key,
  title,
  short_description,
  notice_text,
  is_time_sensitive,
  status,
  valid_from,
  valid_to
) values (
  '2026-08-08'::date,
  'emotion',
  '친구끼리 응원하는 말',
  '힘내라고 할 때 자주 쓰는 표현을 알려주세요 사진으로 보여주세요. 얼굴이 아니어도 괜찮고, 그 감정을 떠올리게 하는 장면이나 물건으로 표현해도 좋아요.',
  ''::text,
  false,
  'published',
  '2026-08-08 12:00:00+00'::timestamptz,
  '2026-08-09 12:00:00+00'::timestamptz
);

insert into public.missions (
  mission_date,
  category_key,
  title,
  short_description,
  notice_text,
  is_time_sensitive,
  status,
  valid_from,
  valid_to
) values (
  '2026-08-09'::date,
  'emotion',
  '울음을 보는 시선',
  '공공장소에서 우는 것에 대한 인식을 사진으로 보여주고 짧게 설명해주세요. 얼굴이 아니어도 괜찮고, 그 감정을 떠올리게 하는 장면이나 물건으로 표현해도 좋아요.',
  ''::text,
  false,
  'published',
  '2026-08-09 12:00:00+00'::timestamptz,
  '2026-08-10 12:00:00+00'::timestamptz
);

insert into public.missions (
  mission_date,
  category_key,
  title,
  short_description,
  notice_text,
  is_time_sensitive,
  status,
  valid_from,
  valid_to
) values (
  '2026-08-10'::date,
  'emotion',
  '놀랐을 때 하는 말',
  '깜짝 놀랐을 때 튀어나오는 표현을 알려주세요 사진으로 보여주세요. 얼굴이 아니어도 괜찮고, 그 감정을 떠올리게 하는 장면이나 물건으로 표현해도 좋아요.',
  ''::text,
  false,
  'published',
  '2026-08-10 12:00:00+00'::timestamptz,
  '2026-08-11 12:00:00+00'::timestamptz
);

insert into public.missions (
  mission_date,
  category_key,
  title,
  short_description,
  notice_text,
  is_time_sensitive,
  status,
  valid_from,
  valid_to
) values (
  '2026-08-11'::date,
  'emotion',
  '수줍음 표현하기',
  '부끄러울 때 보이는 행동이나 표정을 사진으로 보여주세요. 얼굴이 아니어도 괜찮고, 그 감정을 떠올리게 하는 장면이나 물건으로 표현해도 좋아요.',
  ''::text,
  false,
  'published',
  '2026-08-11 12:00:00+00'::timestamptz,
  '2026-08-12 12:00:00+00'::timestamptz
);

insert into public.missions (
  mission_date,
  category_key,
  title,
  short_description,
  notice_text,
  is_time_sensitive,
  status,
  valid_from,
  valid_to
) values (
  '2026-08-12'::date,
  'emotion',
  '존경을 표현하는 방식',
  '존경하는 사람에게 어떤 태도를 보이는지 사진으로 보여주고 짧게 설명해주세요. 얼굴이 아니어도 괜찮고, 그 감정을 떠올리게 하는 장면이나 물건으로 표현해도 좋아요.',
  ''::text,
  false,
  'published',
  '2026-08-12 12:00:00+00'::timestamptz,
  '2026-08-13 12:00:00+00'::timestamptz
);

insert into public.missions (
  mission_date,
  category_key,
  title,
  short_description,
  notice_text,
  is_time_sensitive,
  status,
  valid_from,
  valid_to
) values (
  '2026-08-13'::date,
  'emotion',
  '고생했어를 말하는 법',
  '누군가 수고했을 때 자주 하는 말을 사진으로 보여주세요. 얼굴이 아니어도 괜찮고, 그 감정을 떠올리게 하는 장면이나 물건으로 표현해도 좋아요.',
  ''::text,
  false,
  'published',
  '2026-08-13 12:00:00+00'::timestamptz,
  '2026-08-14 12:00:00+00'::timestamptz
);

insert into public.missions (
  mission_date,
  category_key,
  title,
  short_description,
  notice_text,
  is_time_sensitive,
  status,
  valid_from,
  valid_to
) values (
  '2026-08-14'::date,
  'emotion',
  '축하의 리액션',
  '좋은 소식이 있을 때 주변 반응은 어떤가요 사진으로 보여주세요. 얼굴이 아니어도 괜찮고, 그 감정을 떠올리게 하는 장면이나 물건으로 표현해도 좋아요.',
  ''::text,
  false,
  'published',
  '2026-08-14 12:00:00+00'::timestamptz,
  '2026-08-15 12:00:00+00'::timestamptz
);

insert into public.missions (
  mission_date,
  category_key,
  title,
  short_description,
  notice_text,
  is_time_sensitive,
  status,
  valid_from,
  valid_to
) values (
  '2026-08-15'::date,
  'emotion',
  '애정 표현의 거리감',
  '친구 사이 스킨십이나 애정 표현이 자연스러운지 사진으로 보여주고 짧게 설명해주세요. 얼굴이 아니어도 괜찮고, 그 감정을 떠올리게 하는 장면이나 물건으로 표현해도 좋아요.',
  ''::text,
  false,
  'published',
  '2026-08-15 12:00:00+00'::timestamptz,
  '2026-08-16 12:00:00+00'::timestamptz
);

insert into public.missions (
  mission_date,
  category_key,
  title,
  short_description,
  notice_text,
  is_time_sensitive,
  status,
  valid_from,
  valid_to
) values (
  '2026-08-16'::date,
  'emotion',
  '부정적인 감정 돌려 말하기',
  '싫다고 직접 말하지 않고 표현하는 방식이 있다면 사진으로 보여주세요. 얼굴이 아니어도 괜찮고, 그 감정을 떠올리게 하는 장면이나 물건으로 표현해도 좋아요.',
  ''::text,
  false,
  'published',
  '2026-08-16 12:00:00+00'::timestamptz,
  '2026-08-17 12:00:00+00'::timestamptz
);

insert into public.missions (
  mission_date,
  category_key,
  title,
  short_description,
  notice_text,
  is_time_sensitive,
  status,
  valid_from,
  valid_to
) values (
  '2026-08-17'::date,
  'emotion',
  '감정 숨기기 vs 드러내기',
  '감정을 드러내는 편인지 숨기는 편인지 일상 예시로 사진으로 보여주고 짧게 설명해주세요. 얼굴이 아니어도 괜찮고, 그 감정을 떠올리게 하는 장면이나 물건으로 표현해도 좋아요.',
  ''::text,
  false,
  'published',
  '2026-08-17 12:00:00+00'::timestamptz,
  '2026-08-18 12:00:00+00'::timestamptz
);

insert into public.missions (
  mission_date,
  category_key,
  title,
  short_description,
  notice_text,
  is_time_sensitive,
  status,
  valid_from,
  valid_to
) values (
  '2026-08-18'::date,
  'emotion',
  '부모님께 애정 표현하기',
  '가족 간 애정 표현이 어떤 식으로 이루어지는지 사진으로 보여주세요. 얼굴이 아니어도 괜찮고, 그 감정을 떠올리게 하는 장면이나 물건으로 표현해도 좋아요.',
  ''::text,
  false,
  'published',
  '2026-08-18 12:00:00+00'::timestamptz,
  '2026-08-19 12:00:00+00'::timestamptz
);

insert into public.missions (
  mission_date,
  category_key,
  title,
  short_description,
  notice_text,
  is_time_sensitive,
  status,
  valid_from,
  valid_to
) values (
  '2026-08-19'::date,
  'emotion',
  '친한 사이 농담의 선',
  '친구끼리 놀릴 때 어디까지 괜찮은지 사진으로 보여주고 짧게 설명해주세요. 얼굴이 아니어도 괜찮고, 그 감정을 떠올리게 하는 장면이나 물건으로 표현해도 좋아요.',
  ''::text,
  false,
  'published',
  '2026-08-19 12:00:00+00'::timestamptz,
  '2026-08-20 12:00:00+00'::timestamptz
);

insert into public.missions (
  mission_date,
  category_key,
  title,
  short_description,
  notice_text,
  is_time_sensitive,
  status,
  valid_from,
  valid_to
) values (
  '2026-08-20'::date,
  'emotion',
  '실망했을 때 하는 말',
  '실망을 표현하는 짧은 말이나 표정을 사진으로 보여주세요. 얼굴이 아니어도 괜찮고, 그 감정을 떠올리게 하는 장면이나 물건으로 표현해도 좋아요.',
  ''::text,
  false,
  'published',
  '2026-08-20 12:00:00+00'::timestamptz,
  '2026-08-21 12:00:00+00'::timestamptz
);

insert into public.missions (
  mission_date,
  category_key,
  title,
  short_description,
  notice_text,
  is_time_sensitive,
  status,
  valid_from,
  valid_to
) values (
  '2026-08-21'::date,
  'emotion',
  '감동받았을 때 행동',
  '감동적인 순간에 보통 어떤 반응을 보이나요 사진으로 보여주세요. 얼굴이 아니어도 괜찮고, 그 감정을 떠올리게 하는 장면이나 물건으로 표현해도 좋아요.',
  ''::text,
  false,
  'published',
  '2026-08-21 12:00:00+00'::timestamptz,
  '2026-08-22 12:00:00+00'::timestamptz
);

insert into public.missions (
  mission_date,
  category_key,
  title,
  short_description,
  notice_text,
  is_time_sensitive,
  status,
  valid_from,
  valid_to
) values (
  '2026-08-22'::date,
  'emotion',
  '부끄러운 칭찬 하나',
  '듣기 쑥스럽지만 기분 좋은 칭찬 표현을 하나 알려주세요 사진으로 보여주세요. 얼굴이 아니어도 괜찮고, 그 감정을 떠올리게 하는 장면이나 물건으로 표현해도 좋아요.',
  ''::text,
  false,
  'published',
  '2026-08-22 12:00:00+00'::timestamptz,
  '2026-08-23 12:00:00+00'::timestamptz
);

insert into public.missions (
  mission_date,
  category_key,
  title,
  short_description,
  notice_text,
  is_time_sensitive,
  status,
  valid_from,
  valid_to
) values (
  '2026-08-23'::date,
  'emotion',
  '응원받고 싶은 순간',
  '당신의 나라에서 사람들이 특히 응원을 많이 원하는 순간을 사진으로 보여주세요. 얼굴이 아니어도 괜찮고, 그 감정을 떠올리게 하는 장면이나 물건으로 표현해도 좋아요.',
  ''::text,
  false,
  'published',
  '2026-08-23 12:00:00+00'::timestamptz,
  '2026-08-24 12:00:00+00'::timestamptz
);

insert into public.missions (
  mission_date,
  category_key,
  title,
  short_description,
  notice_text,
  is_time_sensitive,
  status,
  valid_from,
  valid_to
) values (
  '2026-08-24'::date,
  'emotion',
  '침묵의 의미',
  '말이 없는 것이 편안함인지 어색함인지 사진으로 보여주고 짧게 설명해주세요. 얼굴이 아니어도 괜찮고, 그 감정을 떠올리게 하는 장면이나 물건으로 표현해도 좋아요.',
  ''::text,
  false,
  'published',
  '2026-08-24 12:00:00+00'::timestamptz,
  '2026-08-25 12:00:00+00'::timestamptz
);

insert into public.missions (
  mission_date,
  category_key,
  title,
  short_description,
  notice_text,
  is_time_sensitive,
  status,
  valid_from,
  valid_to
) values (
  '2026-08-25'::date,
  'emotion',
  '웃음의 매너',
  '크게 웃는 것이 자연스러운지 조심하는 편인지 사진으로 보여주세요. 얼굴이 아니어도 괜찮고, 그 감정을 떠올리게 하는 장면이나 물건으로 표현해도 좋아요.',
  ''::text,
  false,
  'published',
  '2026-08-25 12:00:00+00'::timestamptz,
  '2026-08-26 12:00:00+00'::timestamptz
);

insert into public.missions (
  mission_date,
  category_key,
  title,
  short_description,
  notice_text,
  is_time_sensitive,
  status,
  valid_from,
  valid_to
) values (
  '2026-08-26'::date,
  'emotion',
  '감정을 담은 이모지',
  '현지에서 자주 쓰는 감정 이모지나 스티커를 사진으로 보여주세요. 얼굴이 아니어도 괜찮고, 그 감정을 떠올리게 하는 장면이나 물건으로 표현해도 좋아요.',
  ''::text,
  false,
  'published',
  '2026-08-26 12:00:00+00'::timestamptz,
  '2026-08-27 12:00:00+00'::timestamptz
);

insert into public.missions (
  mission_date,
  category_key,
  title,
  short_description,
  notice_text,
  is_time_sensitive,
  status,
  valid_from,
  valid_to
) values (
  '2026-08-27'::date,
  'emotion',
  '감정 표현이 달라지는 대상',
  '친구, 가족, 선생님 앞에서 감정 표현이 어떻게 달라지는지 사진으로 보여주고 짧게 설명해주세요. 얼굴이 아니어도 괜찮고, 그 감정을 떠올리게 하는 장면이나 물건으로 표현해도 좋아요.',
  ''::text,
  false,
  'published',
  '2026-08-27 12:00:00+00'::timestamptz,
  '2026-08-28 12:00:00+00'::timestamptz
);

insert into public.missions (
  mission_date,
  category_key,
  title,
  short_description,
  notice_text,
  is_time_sensitive,
  status,
  valid_from,
  valid_to
) values (
  '2026-08-28'::date,
  'emotion',
  '한 단어로 오늘 기분 말하기',
  '오늘 기분을 당신 나라 말 한 단어로 표현하고 뜻을 알려주세요 사진으로 보여주세요. 얼굴이 아니어도 괜찮고, 그 감정을 떠올리게 하는 장면이나 물건으로 표현해도 좋아요.',
  ''::text,
  false,
  'published',
  '2026-08-28 12:00:00+00'::timestamptz,
  '2026-08-29 12:00:00+00'::timestamptz
);

insert into public.missions (
  mission_date,
  category_key,
  title,
  short_description,
  notice_text,
  is_time_sensitive,
  status,
  valid_from,
  valid_to
) values (
  '2026-08-29'::date,
  'fashion',
  '오늘의 평범한 출근/등교룩',
  '평범한 하루에 입는 옷차림을 사진으로 보여주세요. 본인을 찍기 부담되면 옷이나 포인트 아이템만 찍어도 괜찮아요.',
  ''::text,
  false,
  'published',
  '2026-08-29 12:00:00+00'::timestamptz,
  '2026-08-30 12:00:00+00'::timestamptz
);

insert into public.missions (
  mission_date,
  category_key,
  title,
  short_description,
  notice_text,
  is_time_sensitive,
  status,
  valid_from,
  valid_to
) values (
  '2026-08-30'::date,
  'fashion',
  '날씨에 따른 옷 선택',
  '오늘 날씨에 맞춰 어떤 옷을 입는지 사진으로 보여주세요. 본인을 찍기 부담되면 옷이나 포인트 아이템만 찍어도 괜찮아요.',
  ''::text,
  false,
  'published',
  '2026-08-30 12:00:00+00'::timestamptz,
  '2026-08-31 12:00:00+00'::timestamptz
);

insert into public.missions (
  mission_date,
  category_key,
  title,
  short_description,
  notice_text,
  is_time_sensitive,
  status,
  valid_from,
  valid_to
) values (
  '2026-08-31'::date,
  'fashion',
  '학교/직장의 복장 분위기',
  '학교나 회사에서 선호되는 복장 스타일을 사진으로 보여주세요. 본인을 찍기 부담되면 옷이나 포인트 아이템만 찍어도 괜찮아요.',
  ''::text,
  false,
  'published',
  '2026-08-31 12:00:00+00'::timestamptz,
  '2026-09-01 12:00:00+00'::timestamptz
);

insert into public.missions (
  mission_date,
  category_key,
  title,
  short_description,
  notice_text,
  is_time_sensitive,
  status,
  valid_from,
  valid_to
) values (
  '2026-09-01'::date,
  'fashion',
  '길거리에서 많이 보이는 스타일',
  '요즘 거리에서 자주 보이는 스타일 하나를 사진으로 보여주세요. 본인을 찍기 부담되면 옷이나 포인트 아이템만 찍어도 괜찮아요.',
  ''::text,
  false,
  'published',
  '2026-09-01 12:00:00+00'::timestamptz,
  '2026-09-02 12:00:00+00'::timestamptz
);

insert into public.missions (
  mission_date,
  category_key,
  title,
  short_description,
  notice_text,
  is_time_sensitive,
  status,
  valid_from,
  valid_to
) values (
  '2026-09-02'::date,
  'fashion',
  '신발 문화 소개',
  '일상에서 가장 흔히 신는 신발을 사진으로 보여주세요. 본인을 찍기 부담되면 옷이나 포인트 아이템만 찍어도 괜찮아요.',
  ''::text,
  false,
  'published',
  '2026-09-02 12:00:00+00'::timestamptz,
  '2026-09-03 12:00:00+00'::timestamptz
);

insert into public.missions (
  mission_date,
  category_key,
  title,
  short_description,
  notice_text,
  is_time_sensitive,
  status,
  valid_from,
  valid_to
) values (
  '2026-09-03'::date,
  'fashion',
  '액세서리 포인트',
  '현지 사람들이 자주 하는 액세서리 하나를 사진으로 보여주세요. 본인을 찍기 부담되면 옷이나 포인트 아이템만 찍어도 괜찮아요.',
  ''::text,
  false,
  'published',
  '2026-09-03 12:00:00+00'::timestamptz,
  '2026-09-04 12:00:00+00'::timestamptz
);

insert into public.missions (
  mission_date,
  category_key,
  title,
  short_description,
  notice_text,
  is_time_sensitive,
  status,
  valid_from,
  valid_to
) values (
  '2026-09-04'::date,
  'fashion',
  '계절별 필수 아이템',
  '지금 계절에 꼭 필요한 패션 아이템을 사진으로 보여주세요. 본인을 찍기 부담되면 옷이나 포인트 아이템만 찍어도 괜찮아요.',
  ''::text,
  false,
  'published',
  '2026-09-04 12:00:00+00'::timestamptz,
  '2026-09-05 12:00:00+00'::timestamptz
);

insert into public.missions (
  mission_date,
  category_key,
  title,
  short_description,
  notice_text,
  is_time_sensitive,
  status,
  valid_from,
  valid_to
) values (
  '2026-09-05'::date,
  'fashion',
  '집 앞 패션 vs 외출 패션',
  '집 앞에 나갈 때와 약속 갈 때의 차이를 사진으로 보여주세요. 본인을 찍기 부담되면 옷이나 포인트 아이템만 찍어도 괜찮아요.',
  ''::text,
  false,
  'published',
  '2026-09-05 12:00:00+00'::timestamptz,
  '2026-09-06 12:00:00+00'::timestamptz
);

insert into public.missions (
  mission_date,
  category_key,
  title,
  short_description,
  notice_text,
  is_time_sensitive,
  status,
  valid_from,
  valid_to
) values (
  '2026-09-06'::date,
  'fashion',
  '전통 의상 한 요소',
  '전통 의상이나 전통 스타일의 요소를 하나 사진으로 보여주세요. 본인을 찍기 부담되면 옷이나 포인트 아이템만 찍어도 괜찮아요.',
  ''::text,
  false,
  'published',
  '2026-09-06 12:00:00+00'::timestamptz,
  '2026-09-07 12:00:00+00'::timestamptz
);

insert into public.missions (
  mission_date,
  category_key,
  title,
  short_description,
  notice_text,
  is_time_sensitive,
  status,
  valid_from,
  valid_to
) values (
  '2026-09-07'::date,
  'fashion',
  '격식 있는 자리의 복장',
  '결혼식, 면접, 행사에 갈 때 어떤 옷을 입는지 사진으로 보여주세요. 본인을 찍기 부담되면 옷이나 포인트 아이템만 찍어도 괜찮아요.',
  ''::text,
  false,
  'published',
  '2026-09-07 12:00:00+00'::timestamptz,
  '2026-09-08 12:00:00+00'::timestamptz
);

insert into public.missions (
  mission_date,
  category_key,
  title,
  short_description,
  notice_text,
  is_time_sensitive,
  status,
  valid_from,
  valid_to
) values (
  '2026-09-08'::date,
  'fashion',
  '학생들이 좋아하는 브랜드/스타일',
  '학생들 사이에서 인기 있는 브랜드나 스타일을 사진으로 보여주세요. 본인을 찍기 부담되면 옷이나 포인트 아이템만 찍어도 괜찮아요.',
  ''::text,
  false,
  'published',
  '2026-09-08 12:00:00+00'::timestamptz,
  '2026-09-09 12:00:00+00'::timestamptz
);

insert into public.missions (
  mission_date,
  category_key,
  title,
  short_description,
  notice_text,
  is_time_sensitive,
  status,
  valid_from,
  valid_to
) values (
  '2026-09-09'::date,
  'fashion',
  '색깔 선호도',
  '옷에서 자주 보이는 색감이나 조합을 사진으로 보여주세요. 본인을 찍기 부담되면 옷이나 포인트 아이템만 찍어도 괜찮아요.',
  ''::text,
  false,
  'published',
  '2026-09-09 12:00:00+00'::timestamptz,
  '2026-09-10 12:00:00+00'::timestamptz
);

insert into public.missions (
  mission_date,
  category_key,
  title,
  short_description,
  notice_text,
  is_time_sensitive,
  status,
  valid_from,
  valid_to
) values (
  '2026-09-10'::date,
  'fashion',
  '패션과 체형 인식',
  '옷을 고를 때 편안함과 핏 중 무엇을 더 중시하나요 사진으로 보여주세요. 본인을 찍기 부담되면 옷이나 포인트 아이템만 찍어도 괜찮아요.',
  ''::text,
  false,
  'published',
  '2026-09-10 12:00:00+00'::timestamptz,
  '2026-09-11 12:00:00+00'::timestamptz
);

insert into public.missions (
  mission_date,
  category_key,
  title,
  short_description,
  notice_text,
  is_time_sensitive,
  status,
  valid_from,
  valid_to
) values (
  '2026-09-11'::date,
  'fashion',
  '비 오는 날 패션',
  '비 오는 날 사람들의 옷차림과 준비물을 사진으로 보여주세요. 본인을 찍기 부담되면 옷이나 포인트 아이템만 찍어도 괜찮아요.',
  ''::text,
  false,
  'published',
  '2026-09-11 12:00:00+00'::timestamptz,
  '2026-09-12 12:00:00+00'::timestamptz
);

insert into public.missions (
  mission_date,
  category_key,
  title,
  short_description,
  notice_text,
  is_time_sensitive,
  status,
  valid_from,
  valid_to
) values (
  '2026-09-12'::date,
  'fashion',
  '운동복의 일상화',
  '운동복을 평소에도 자주 입는지 사진으로 보여주세요. 본인을 찍기 부담되면 옷이나 포인트 아이템만 찍어도 괜찮아요.',
  ''::text,
  false,
  'published',
  '2026-09-12 12:00:00+00'::timestamptz,
  '2026-09-13 12:00:00+00'::timestamptz
);

insert into public.missions (
  mission_date,
  category_key,
  title,
  short_description,
  notice_text,
  is_time_sensitive,
  status,
  valid_from,
  valid_to
) values (
  '2026-09-13'::date,
  'fashion',
  '머리 스타일 유행',
  '요즘 인기 있는 헤어스타일을 사진으로 보여주세요. 본인을 찍기 부담되면 옷이나 포인트 아이템만 찍어도 괜찮아요.',
  ''::text,
  false,
  'published',
  '2026-09-13 12:00:00+00'::timestamptz,
  '2026-09-14 12:00:00+00'::timestamptz
);

insert into public.missions (
  mission_date,
  category_key,
  title,
  short_description,
  notice_text,
  is_time_sensitive,
  status,
  valid_from,
  valid_to
) values (
  '2026-09-14'::date,
  'fashion',
  '가방에 담긴 문화',
  '사람들이 자주 메는 가방 종류와 이유를 사진으로 보여주세요. 본인을 찍기 부담되면 옷이나 포인트 아이템만 찍어도 괜찮아요.',
  ''::text,
  false,
  'published',
  '2026-09-14 12:00:00+00'::timestamptz,
  '2026-09-15 12:00:00+00'::timestamptz
);

insert into public.missions (
  mission_date,
  category_key,
  title,
  short_description,
  notice_text,
  is_time_sensitive,
  status,
  valid_from,
  valid_to
) values (
  '2026-09-15'::date,
  'fashion',
  '옷차림으로 보는 세대 차이',
  '젊은 세대와 부모 세대의 스타일 차이를 사진으로 보여주고 짧게 설명해주세요. 본인을 찍기 부담되면 옷이나 포인트 아이템만 찍어도 괜찮아요.',
  ''::text,
  false,
  'published',
  '2026-09-15 12:00:00+00'::timestamptz,
  '2026-09-16 12:00:00+00'::timestamptz
);

insert into public.missions (
  mission_date,
  category_key,
  title,
  short_description,
  notice_text,
  is_time_sensitive,
  status,
  valid_from,
  valid_to
) values (
  '2026-09-16'::date,
  'fashion',
  '노출/보수적 기준',
  '어떤 옷차림이 과하다고 느껴지는지 사진으로 보여주고 짧게 설명해주세요. 본인을 찍기 부담되면 옷이나 포인트 아이템만 찍어도 괜찮아요.',
  ''::text,
  false,
  'published',
  '2026-09-16 12:00:00+00'::timestamptz,
  '2026-09-17 12:00:00+00'::timestamptz
);

insert into public.missions (
  mission_date,
  category_key,
  title,
  short_description,
  notice_text,
  is_time_sensitive,
  status,
  valid_from,
  valid_to
) values (
  '2026-09-17'::date,
  'fashion',
  '사진 찍을 때 꾸미는 포인트',
  '사진 찍는 날 유독 신경 쓰는 패션 포인트를 사진으로 보여주세요. 본인을 찍기 부담되면 옷이나 포인트 아이템만 찍어도 괜찮아요.',
  ''::text,
  false,
  'published',
  '2026-09-17 12:00:00+00'::timestamptz,
  '2026-09-18 12:00:00+00'::timestamptz
);

insert into public.missions (
  mission_date,
  category_key,
  title,
  short_description,
  notice_text,
  is_time_sensitive,
  status,
  valid_from,
  valid_to
) values (
  '2026-09-18'::date,
  'fashion',
  '유니폼 문화',
  '교복, 회사 유니폼, 단체복 문화가 있다면 사진으로 보여주세요. 본인을 찍기 부담되면 옷이나 포인트 아이템만 찍어도 괜찮아요.',
  ''::text,
  false,
  'published',
  '2026-09-18 12:00:00+00'::timestamptz,
  '2026-09-19 12:00:00+00'::timestamptz
);

insert into public.missions (
  mission_date,
  category_key,
  title,
  short_description,
  notice_text,
  is_time_sensitive,
  status,
  valid_from,
  valid_to
) values (
  '2026-09-19'::date,
  'fashion',
  '로컬 쇼핑 장소',
  '옷을 자주 사는 장소(시장, 쇼핑몰, 온라인)를 사진으로 보여주세요. 본인을 찍기 부담되면 옷이나 포인트 아이템만 찍어도 괜찮아요.',
  ''::text,
  false,
  'published',
  '2026-09-19 12:00:00+00'::timestamptz,
  '2026-09-20 12:00:00+00'::timestamptz
);

insert into public.missions (
  mission_date,
  category_key,
  title,
  short_description,
  notice_text,
  is_time_sensitive,
  status,
  valid_from,
  valid_to
) values (
  '2026-09-20'::date,
  'fashion',
  '중고/빈티지 패션',
  '중고 옷이나 빈티지 스타일이 인기 있는지 사진으로 보여주세요. 본인을 찍기 부담되면 옷이나 포인트 아이템만 찍어도 괜찮아요.',
  ''::text,
  false,
  'published',
  '2026-09-20 12:00:00+00'::timestamptz,
  '2026-09-21 12:00:00+00'::timestamptz
);

insert into public.missions (
  mission_date,
  category_key,
  title,
  short_description,
  notice_text,
  is_time_sensitive,
  status,
  valid_from,
  valid_to
) values (
  '2026-09-21'::date,
  'fashion',
  '데일리 메이크업 감성',
  '일상 메이크업이 진한 편인지 자연스러운 편인지 사진으로 보여주세요. 본인을 찍기 부담되면 옷이나 포인트 아이템만 찍어도 괜찮아요.',
  ''::text,
  false,
  'published',
  '2026-09-21 12:00:00+00'::timestamptz,
  '2026-09-22 12:00:00+00'::timestamptz
);

insert into public.missions (
  mission_date,
  category_key,
  title,
  short_description,
  notice_text,
  is_time_sensitive,
  status,
  valid_from,
  valid_to
) values (
  '2026-09-22'::date,
  'fashion',
  '패션 금기 하나',
  '현지에서 특정 상황에 피하는 옷차림이 있다면 사진으로 보여주세요. 본인을 찍기 부담되면 옷이나 포인트 아이템만 찍어도 괜찮아요.',
  ''::text,
  false,
  'published',
  '2026-09-22 12:00:00+00'::timestamptz,
  '2026-09-23 12:00:00+00'::timestamptz
);

insert into public.missions (
  mission_date,
  category_key,
  title,
  short_description,
  notice_text,
  is_time_sensitive,
  status,
  valid_from,
  valid_to
) values (
  '2026-09-23'::date,
  'fashion',
  '특별한 날 꾸미기',
  '축제, 파티, 데이트 날 어떤 식으로 꾸미는지 사진으로 보여주세요. 본인을 찍기 부담되면 옷이나 포인트 아이템만 찍어도 괜찮아요.',
  ''::text,
  false,
  'published',
  '2026-09-23 12:00:00+00'::timestamptz,
  '2026-09-24 12:00:00+00'::timestamptz
);

insert into public.missions (
  mission_date,
  category_key,
  title,
  short_description,
  notice_text,
  is_time_sensitive,
  status,
  valid_from,
  valid_to
) values (
  '2026-09-24'::date,
  'fashion',
  '편안함이 중요한 패션',
  '멋보다 편안함이 더 중요한 순간의 옷차림을 사진으로 보여주세요. 본인을 찍기 부담되면 옷이나 포인트 아이템만 찍어도 괜찮아요.',
  ''::text,
  false,
  'published',
  '2026-09-24 12:00:00+00'::timestamptz,
  '2026-09-25 12:00:00+00'::timestamptz
);

insert into public.missions (
  mission_date,
  category_key,
  title,
  short_description,
  notice_text,
  is_time_sensitive,
  status,
  valid_from,
  valid_to
) values (
  '2026-09-25'::date,
  'fashion',
  '현지 패션 아이콘',
  '요즘 많이 따라 입는 유명인 스타일이 있다면 사진으로 보여주세요. 본인을 찍기 부담되면 옷이나 포인트 아이템만 찍어도 괜찮아요.',
  ''::text,
  false,
  'published',
  '2026-09-25 12:00:00+00'::timestamptz,
  '2026-09-26 12:00:00+00'::timestamptz
);

insert into public.missions (
  mission_date,
  category_key,
  title,
  short_description,
  notice_text,
  is_time_sensitive,
  status,
  valid_from,
  valid_to
) values (
  '2026-09-26'::date,
  'fashion',
  '나이와 패션의 관계',
  '나이에 따라 입어야 한다고 여겨지는 스타일이 있나요 사진으로 보여주세요. 본인을 찍기 부담되면 옷이나 포인트 아이템만 찍어도 괜찮아요.',
  ''::text,
  false,
  'published',
  '2026-09-26 12:00:00+00'::timestamptz,
  '2026-09-27 12:00:00+00'::timestamptz
);

insert into public.missions (
  mission_date,
  category_key,
  title,
  short_description,
  notice_text,
  is_time_sensitive,
  status,
  valid_from,
  valid_to
) values (
  '2026-09-27'::date,
  'fashion',
  '내 나라를 보여주는 룩',
  '당신 나라 분위기를 가장 잘 보여주는 스타일을 사진으로 보여주세요. 본인을 찍기 부담되면 옷이나 포인트 아이템만 찍어도 괜찮아요.',
  ''::text,
  false,
  'published',
  '2026-09-27 12:00:00+00'::timestamptz,
  '2026-09-28 12:00:00+00'::timestamptz
);

insert into public.missions (
  mission_date,
  category_key,
  title,
  short_description,
  notice_text,
  is_time_sensitive,
  status,
  valid_from,
  valid_to
) values (
  '2026-09-28'::date,
  'study',
  '나의 공부 공간 소개',
  '집, 학교, 카페 중 어디서 공부하는지 사진으로 보여주세요. 사람 얼굴 없이 책상, 필기, 도구, 쉬는 순간만 찍어도 괜찮아요.',
  ''::text,
  false,
  'published',
  '2026-09-28 12:00:00+00'::timestamptz,
  '2026-09-29 12:00:00+00'::timestamptz
);

insert into public.missions (
  mission_date,
  category_key,
  title,
  short_description,
  notice_text,
  is_time_sensitive,
  status,
  valid_from,
  valid_to
) values (
  '2026-09-29'::date,
  'study',
  '시험기간 필수템',
  '시험기간에 꼭 챙기는 물건 3가지를 사진으로 보여주세요. 사람 얼굴 없이 책상, 필기, 도구, 쉬는 순간만 찍어도 괜찮아요.',
  ''::text,
  false,
  'published',
  '2026-09-29 12:00:00+00'::timestamptz,
  '2026-09-30 12:00:00+00'::timestamptz
);

insert into public.missions (
  mission_date,
  category_key,
  title,
  short_description,
  notice_text,
  is_time_sensitive,
  status,
  valid_from,
  valid_to
) values (
  '2026-09-30'::date,
  'study',
  '학교/학원 후 루틴',
  '수업이 끝난 뒤 보통 무엇을 하는지 사진으로 보여주세요. 사람 얼굴 없이 책상, 필기, 도구, 쉬는 순간만 찍어도 괜찮아요.',
  ''::text,
  false,
  'published',
  '2026-09-30 12:00:00+00'::timestamptz,
  '2026-10-01 12:00:00+00'::timestamptz
);

insert into public.missions (
  mission_date,
  category_key,
  title,
  short_description,
  notice_text,
  is_time_sensitive,
  status,
  valid_from,
  valid_to
) values (
  '2026-10-01'::date,
  'study',
  '필기 스타일 보여주기',
  '손필기, 태블릿, 노트 앱 중 어떤 방식을 주로 쓰는지 사진으로 보여주세요. 사람 얼굴 없이 책상, 필기, 도구, 쉬는 순간만 찍어도 괜찮아요.',
  ''::text,
  false,
  'published',
  '2026-10-01 12:00:00+00'::timestamptz,
  '2026-10-02 12:00:00+00'::timestamptz
);

insert into public.missions (
  mission_date,
  category_key,
  title,
  short_description,
  notice_text,
  is_time_sensitive,
  status,
  valid_from,
  valid_to
) values (
  '2026-10-02'::date,
  'study',
  '가장 조용한 공부 장소',
  '집중이 잘 되는 장소를 사진으로 보여주세요. 사람 얼굴 없이 책상, 필기, 도구, 쉬는 순간만 찍어도 괜찮아요.',
  ''::text,
  false,
  'published',
  '2026-10-02 12:00:00+00'::timestamptz,
  '2026-10-03 12:00:00+00'::timestamptz
);

insert into public.missions (
  mission_date,
  category_key,
  title,
  short_description,
  notice_text,
  is_time_sensitive,
  status,
  valid_from,
  valid_to
) values (
  '2026-10-03'::date,
  'study',
  '친구와 함께 공부하기',
  '스터디를 자주 하는지, 혼자 공부하는지 사진으로 보여주세요. 사람 얼굴 없이 책상, 필기, 도구, 쉬는 순간만 찍어도 괜찮아요.',
  ''::text,
  false,
  'published',
  '2026-10-03 12:00:00+00'::timestamptz,
  '2026-10-04 12:00:00+00'::timestamptz
);

insert into public.missions (
  mission_date,
  category_key,
  title,
  short_description,
  notice_text,
  is_time_sensitive,
  status,
  valid_from,
  valid_to
) values (
  '2026-10-04'::date,
  'study',
  '숙제 문화 설명',
  '숙제가 많은 편인지, 어떤 형식이 많은지 사진으로 보여주고 짧게 설명해주세요. 사람 얼굴 없이 책상, 필기, 도구, 쉬는 순간만 찍어도 괜찮아요.',
  ''::text,
  false,
  'published',
  '2026-10-04 12:00:00+00'::timestamptz,
  '2026-10-05 12:00:00+00'::timestamptz
);

insert into public.missions (
  mission_date,
  category_key,
  title,
  short_description,
  notice_text,
  is_time_sensitive,
  status,
  valid_from,
  valid_to
) values (
  '2026-10-05'::date,
  'study',
  '시험 전날 풍경',
  '시험 전날 학생들의 분위기를 사진으로 보여주세요. 사람 얼굴 없이 책상, 필기, 도구, 쉬는 순간만 찍어도 괜찮아요.',
  ''::text,
  false,
  'published',
  '2026-10-05 12:00:00+00'::timestamptz,
  '2026-10-06 12:00:00+00'::timestamptz
);

insert into public.missions (
  mission_date,
  category_key,
  title,
  short_description,
  notice_text,
  is_time_sensitive,
  status,
  valid_from,
  valid_to
) values (
  '2026-10-06'::date,
  'study',
  '공부할 때 듣는 것',
  '음악, 백색소음, 완전한 정적 중 무엇을 선호하는지 사진으로 보여주세요. 사람 얼굴 없이 책상, 필기, 도구, 쉬는 순간만 찍어도 괜찮아요.',
  ''::text,
  false,
  'published',
  '2026-10-06 12:00:00+00'::timestamptz,
  '2026-10-07 12:00:00+00'::timestamptz
);

insert into public.missions (
  mission_date,
  category_key,
  title,
  short_description,
  notice_text,
  is_time_sensitive,
  status,
  valid_from,
  valid_to
) values (
  '2026-10-07'::date,
  'study',
  '학교 점심시간과 공부',
  '점심시간에도 공부하는 분위기가 있는지 사진으로 보여주고 짧게 설명해주세요. 사람 얼굴 없이 책상, 필기, 도구, 쉬는 순간만 찍어도 괜찮아요.',
  ''::text,
  false,
  'published',
  '2026-10-07 12:00:00+00'::timestamptz,
  '2026-10-08 12:00:00+00'::timestamptz
);

insert into public.missions (
  mission_date,
  category_key,
  title,
  short_description,
  notice_text,
  is_time_sensitive,
  status,
  valid_from,
  valid_to
) values (
  '2026-10-08'::date,
  'study',
  '과외/학원 문화',
  '사교육이 흔한지, 어떤 식으로 이루어지는지 사진으로 보여주세요. 사람 얼굴 없이 책상, 필기, 도구, 쉬는 순간만 찍어도 괜찮아요.',
  ''::text,
  false,
  'published',
  '2026-10-08 12:00:00+00'::timestamptz,
  '2026-10-09 12:00:00+00'::timestamptz
);

insert into public.missions (
  mission_date,
  category_key,
  title,
  short_description,
  notice_text,
  is_time_sensitive,
  status,
  valid_from,
  valid_to
) values (
  '2026-10-09'::date,
  'study',
  '선생님과 학생의 거리감',
  '질문하기 편한 분위기인지 사진으로 보여주세요. 사람 얼굴 없이 책상, 필기, 도구, 쉬는 순간만 찍어도 괜찮아요.',
  ''::text,
  false,
  'published',
  '2026-10-09 12:00:00+00'::timestamptz,
  '2026-10-10 12:00:00+00'::timestamptz
);

insert into public.missions (
  mission_date,
  category_key,
  title,
  short_description,
  notice_text,
  is_time_sensitive,
  status,
  valid_from,
  valid_to
) values (
  '2026-10-10'::date,
  'study',
  '발표 수업 문화',
  '발표를 자주 하는지, 어려워하는지 사진으로 보여주고 짧게 설명해주세요. 사람 얼굴 없이 책상, 필기, 도구, 쉬는 순간만 찍어도 괜찮아요.',
  ''::text,
  false,
  'published',
  '2026-10-10 12:00:00+00'::timestamptz,
  '2026-10-11 12:00:00+00'::timestamptz
);

insert into public.missions (
  mission_date,
  category_key,
  title,
  short_description,
  notice_text,
  is_time_sensitive,
  status,
  valid_from,
  valid_to
) values (
  '2026-10-11'::date,
  'study',
  '교실 자리 배치',
  '교실이나 강의실 자리가 어떻게 구성되는지 사진으로 보여주세요. 사람 얼굴 없이 책상, 필기, 도구, 쉬는 순간만 찍어도 괜찮아요.',
  ''::text,
  false,
  'published',
  '2026-10-11 12:00:00+00'::timestamptz,
  '2026-10-12 12:00:00+00'::timestamptz
);

insert into public.missions (
  mission_date,
  category_key,
  title,
  short_description,
  notice_text,
  is_time_sensitive,
  status,
  valid_from,
  valid_to
) values (
  '2026-10-12'::date,
  'study',
  '학교 규칙 하나',
  '학교에서 지켜야 하는 독특한 규칙이 있다면 사진으로 보여주세요. 사람 얼굴 없이 책상, 필기, 도구, 쉬는 순간만 찍어도 괜찮아요.',
  ''::text,
  false,
  'published',
  '2026-10-12 12:00:00+00'::timestamptz,
  '2026-10-13 12:00:00+00'::timestamptz
);

insert into public.missions (
  mission_date,
  category_key,
  title,
  short_description,
  notice_text,
  is_time_sensitive,
  status,
  valid_from,
  valid_to
) values (
  '2026-10-13'::date,
  'study',
  '공부 스트레스 해소법',
  '공부하다 지칠 때 어떻게 쉬는지 사진으로 보여주세요. 사람 얼굴 없이 책상, 필기, 도구, 쉬는 순간만 찍어도 괜찮아요.',
  ''::text,
  false,
  'published',
  '2026-10-13 12:00:00+00'::timestamptz,
  '2026-10-14 12:00:00+00'::timestamptz
);

insert into public.missions (
  mission_date,
  category_key,
  title,
  short_description,
  notice_text,
  is_time_sensitive,
  status,
  valid_from,
  valid_to
) values (
  '2026-10-14'::date,
  'study',
  '시험 성적 공유 문화',
  '친구끼리 성적을 잘 공유하는지 사진으로 보여주고 짧게 설명해주세요. 사람 얼굴 없이 책상, 필기, 도구, 쉬는 순간만 찍어도 괜찮아요.',
  ''::text,
  false,
  'published',
  '2026-10-14 12:00:00+00'::timestamptz,
  '2026-10-15 12:00:00+00'::timestamptz
);

insert into public.missions (
  mission_date,
  category_key,
  title,
  short_description,
  notice_text,
  is_time_sensitive,
  status,
  valid_from,
  valid_to
) values (
  '2026-10-15'::date,
  'study',
  '도서관 자리 문화',
  '도서관에서 자리를 맡거나 조용히 하는 규칙을 사진으로 보여주세요. 사람 얼굴 없이 책상, 필기, 도구, 쉬는 순간만 찍어도 괜찮아요.',
  ''::text,
  false,
  'published',
  '2026-10-15 12:00:00+00'::timestamptz,
  '2026-10-16 12:00:00+00'::timestamptz
);

insert into public.missions (
  mission_date,
  category_key,
  title,
  short_description,
  notice_text,
  is_time_sensitive,
  status,
  valid_from,
  valid_to
) values (
  '2026-10-16'::date,
  'study',
  '유명한 공부 앱/도구',
  '학생들이 많이 쓰는 앱이나 사이트를 사진으로 보여주세요. 사람 얼굴 없이 책상, 필기, 도구, 쉬는 순간만 찍어도 괜찮아요.',
  ''::text,
  false,
  'published',
  '2026-10-16 12:00:00+00'::timestamptz,
  '2026-10-17 12:00:00+00'::timestamptz
);

insert into public.missions (
  mission_date,
  category_key,
  title,
  short_description,
  notice_text,
  is_time_sensitive,
  status,
  valid_from,
  valid_to
) values (
  '2026-10-17'::date,
  'study',
  '암기하는 방법',
  '외울 때 자주 쓰는 나만의 방법을 공유해주세요 사진으로 보여주세요. 사람 얼굴 없이 책상, 필기, 도구, 쉬는 순간만 찍어도 괜찮아요.',
  ''::text,
  false,
  'published',
  '2026-10-17 12:00:00+00'::timestamptz,
  '2026-10-18 12:00:00+00'::timestamptz
);

insert into public.missions (
  mission_date,
  category_key,
  title,
  short_description,
  notice_text,
  is_time_sensitive,
  status,
  valid_from,
  valid_to
) values (
  '2026-10-18'::date,
  'study',
  '학교 행사와 공부 균형',
  '축제나 운동회가 공부 분위기에 어떤 영향을 주는지 사진으로 보여주고 짧게 설명해주세요. 사람 얼굴 없이 책상, 필기, 도구, 쉬는 순간만 찍어도 괜찮아요.',
  ''::text,
  false,
  'published',
  '2026-10-18 12:00:00+00'::timestamptz,
  '2026-10-19 12:00:00+00'::timestamptz
);

insert into public.missions (
  mission_date,
  category_key,
  title,
  short_description,
  notice_text,
  is_time_sensitive,
  status,
  valid_from,
  valid_to
) values (
  '2026-10-19'::date,
  'study',
  '부모님의 공부 기대',
  '가정에서 공부를 얼마나 중요하게 여기는지 사진으로 보여주세요. 사람 얼굴 없이 책상, 필기, 도구, 쉬는 순간만 찍어도 괜찮아요.',
  ''::text,
  false,
  'published',
  '2026-10-19 12:00:00+00'::timestamptz,
  '2026-10-20 12:00:00+00'::timestamptz
);

insert into public.missions (
  mission_date,
  category_key,
  title,
  short_description,
  notice_text,
  is_time_sensitive,
  status,
  valid_from,
  valid_to
) values (
  '2026-10-20'::date,
  'study',
  '좋은 학생의 이미지',
  '당신 나라에서 ‘공부 잘하는 학생’ 이미지를 사진으로 보여주고 짧게 설명해주세요. 사람 얼굴 없이 책상, 필기, 도구, 쉬는 순간만 찍어도 괜찮아요.',
  ''::text,
  false,
  'published',
  '2026-10-20 12:00:00+00'::timestamptz,
  '2026-10-21 12:00:00+00'::timestamptz
);

insert into public.missions (
  mission_date,
  category_key,
  title,
  short_description,
  notice_text,
  is_time_sensitive,
  status,
  valid_from,
  valid_to
) values (
  '2026-10-21'::date,
  'study',
  '방학 숙제 문화',
  '방학 동안 어떤 공부를 하는지 사진으로 보여주세요. 사람 얼굴 없이 책상, 필기, 도구, 쉬는 순간만 찍어도 괜찮아요.',
  ''::text,
  false,
  'published',
  '2026-10-21 12:00:00+00'::timestamptz,
  '2026-10-22 12:00:00+00'::timestamptz
);

insert into public.missions (
  mission_date,
  category_key,
  title,
  short_description,
  notice_text,
  is_time_sensitive,
  status,
  valid_from,
  valid_to
) values (
  '2026-10-22'::date,
  'study',
  '새벽 공부 vs 밤 공부',
  '학생들이 주로 언제 공부하는지 사진으로 보여주세요. 사람 얼굴 없이 책상, 필기, 도구, 쉬는 순간만 찍어도 괜찮아요.',
  ''::text,
  false,
  'published',
  '2026-10-22 12:00:00+00'::timestamptz,
  '2026-10-23 12:00:00+00'::timestamptz
);

insert into public.missions (
  mission_date,
  category_key,
  title,
  short_description,
  notice_text,
  is_time_sensitive,
  status,
  valid_from,
  valid_to
) values (
  '2026-10-23'::date,
  'study',
  '시험 끝난 날의 분위기',
  '시험이 끝난 직후 학생들은 그 장면이나 관련 물건을 사진으로 보여주세요. 사람 얼굴 없이 책상, 필기, 도구, 쉬는 순간만 찍어도 괜찮아요.',
  ''::text,
  false,
  'published',
  '2026-10-23 12:00:00+00'::timestamptz,
  '2026-10-24 12:00:00+00'::timestamptz
);

insert into public.missions (
  mission_date,
  category_key,
  title,
  short_description,
  notice_text,
  is_time_sensitive,
  status,
  valid_from,
  valid_to
) values (
  '2026-10-24'::date,
  'study',
  '교복과 공부 몰입',
  '교복이 공부 분위기에 영향을 준다고 느끼는지 사진으로 보여주고 짧게 설명해주세요. 사람 얼굴 없이 책상, 필기, 도구, 쉬는 순간만 찍어도 괜찮아요.',
  ''::text,
  false,
  'published',
  '2026-10-24 12:00:00+00'::timestamptz,
  '2026-10-25 12:00:00+00'::timestamptz
);

insert into public.missions (
  mission_date,
  category_key,
  title,
  short_description,
  notice_text,
  is_time_sensitive,
  status,
  valid_from,
  valid_to
) values (
  '2026-10-25'::date,
  'study',
  '외국어 공부 방식',
  '영어 혹은 외국어를 어떻게 공부하는지 사진으로 보여주세요. 사람 얼굴 없이 책상, 필기, 도구, 쉬는 순간만 찍어도 괜찮아요.',
  ''::text,
  false,
  'published',
  '2026-10-25 12:00:00+00'::timestamptz,
  '2026-10-26 12:00:00+00'::timestamptz
);

insert into public.missions (
  mission_date,
  category_key,
  title,
  short_description,
  notice_text,
  is_time_sensitive,
  status,
  valid_from,
  valid_to
) values (
  '2026-10-26'::date,
  'study',
  '학교에서 가장 좋아하는 공간',
  '공부와 쉬기를 동시에 할 수 있는 공간을 사진으로 보여주세요. 사람 얼굴 없이 책상, 필기, 도구, 쉬는 순간만 찍어도 괜찮아요.',
  ''::text,
  false,
  'published',
  '2026-10-26 12:00:00+00'::timestamptz,
  '2026-10-27 12:00:00+00'::timestamptz
);

insert into public.missions (
  mission_date,
  category_key,
  title,
  short_description,
  notice_text,
  is_time_sensitive,
  status,
  valid_from,
  valid_to
) values (
  '2026-10-27'::date,
  'study',
  '우리 나라 교육 문화를 한 장면으로',
  '당신 나라의 공부 문화를 가장 잘 보여주는 장면을 설명하거나 사진으로 사진으로 보여주세요. 사람 얼굴 없이 책상, 필기, 도구, 쉬는 순간만 찍어도 괜찮아요.',
  ''::text,
  false,
  'published',
  '2026-10-27 12:00:00+00'::timestamptz,
  '2026-10-28 12:00:00+00'::timestamptz
);

commit;
